#!/usr/bin/env node
/**
 * stress/harness-e2e.mjs — S7: real harness CLIs against the stress Action Hub.
 *
 * Owner: builder-9. Binding contract: /tmp/action-hub-stress/CONTRACT.md.
 *
 * Fully isolated: every run uses a temp HOME / XDG dirs / ACTION_HUB_CONFIG /
 * ACTION_HUB_SKILLS_DIR / PI_CODING_AGENT_DIR. The user's real ~/.pi, ~/.codex,
 * ~/.claude, and opencode configs are never modified; harness credentials come
 * from the user's login state copied ONLY into the run's temp directory (never
 * committed, never written back).
 *
 * What it does:
 *   1. Builds fixtures if stress/.generated is not populated yet (deterministic,
 *      seeded, contract format: skills/<slug>/SKILL.md, tools/<serverId>.json,
 *      servers.json with autoDiscover:false). When builder-1/-4/-2 generators
 *      exist and have produced .generated, their outputs are used as-is.
 *   2. Installs the stress hub into each real harness CLI via
 *      `action-hub harness <target> install --write` (temp config locations).
 *   3. Asks each harness (pi -p, codex exec, claude -p, opencode run) to find a
 *      needle action among the catalog, load/execute it, and print a marker.
 *   4. Measures per harness: needle found + loaded, wall time, search output
 *      size (context fit), and emits a machine-readable JSON summary (last
 *      stdout line + stress/.generated/results/harness-e2e.json).
 *   5. --mode daemon: 3 harnesses run concurrently against ONE shared daemon.
 *
 * Usage:
 *   node stress/harness-e2e.mjs [--harnesses pi,codex,claude,opencode]
 *        [--mode standalone|daemon] [--filler-skills N] [--filler-tools N]
 *        [--timeout secs] [--keep]
 */

import { spawn, spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir, userInfo } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const argv = process.argv.slice(2);
function arg(name, fallback) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && argv[i + 1] !== undefined ? argv[i + 1] : fallback;
}
const flag = (name) => argv.includes(`--${name}`);

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STRESS = join(REPO, "stress");
const GEN = join(STRESS, ".generated");
const RESULTS = join(GEN, "results");
const TIMEOUT_MS = Number(arg("timeout", "240")) * 1000;
const HARNESS_LIST = String(arg("harnesses", "pi,codex,claude,opencode")).split(",");
const MODE = String(arg("mode", "standalone"));
const KEEP = flag("keep");
const FILLER_SKILLS = Number(arg("filler-skills", "150"));
const FILLER_TOOLS_PER_SERVER = Number(arg("filler-tools", "80"));

const NEEDLE_SLUG = "needle-quantum-lattice";
const NEEDLE_SKILL_PASSPHRASE = "LATTICE-PASSPHRASE-7K3F-Q9";
const NEEDLE_TOOL_SERVER = "needle-archive";
const NEEDLE_TOOL_NAME = "find_needle_lattice";
const NEEDLE_TOOL_TOKEN = "NEEDLE-TOKEN-A9F2-LATTICE";
const NEEDLE_SKILL_QUERY = "quantum lattice archive retrieval passphrase";
const NEEDLE_TOOL_QUERY = "lattice archive needle finder";
const SKILL_MARKER = "NEEDLE-SKILL-OK";
const TOOL_MARKER = "NEEDLE-TOOL-OK";

/** Stand-in fake MCP stdio server (supports the needleToken behavior). */
const MINI_SERVER_SRC = `#!/usr/bin/env node
// GENERATED by stress/harness-e2e.mjs (stand-in for fake-mcp-server.mjs). Do not edit.
import { createInterface } from "node:readline";
import { readFileSync } from "node:fs";
const manifestPath = process.argv[process.argv.indexOf("--manifest") + 1];
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const rl = createInterface({ input: process.stdin });
function send(msg) { process.stdout.write(JSON.stringify(msg) + "\\n"); }
rl.on("line", (line) => {
  if (!line.trim()) return;
  let req; try { req = JSON.parse(line); } catch { return; }
  const { id, method, params } = req;
  if (method === "initialize") return send({ jsonrpc: "2.0", id, result: { protocolVersion: params?.protocolVersion ?? "2025-06-18", capabilities: { tools: {} }, serverInfo: { name: manifest.serverId, version: "1.0.0" } } });
  if (method === "notifications/initialized") return;
  if (method === "tools/list") return send({ jsonrpc: "2.0", id, result: { tools: manifest.tools.map((t) => ({ name: t.name, description: t.description, inputSchema: t.inputSchema, annotations: t.annotations })) } });
  if (method === "tools/call") {
    const tool = manifest.tools.find((t) => t.name === params?.name);
    if (!tool) return send({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: "unknown tool" }], isError: true } });
    const needle = tool.behavior?.needleToken ? "\\nARCHIVE_TOKEN: " + tool.behavior.needleToken + "\\n" : "";
    return send({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: "ok " + tool.name + needle }] } });
  }
  send({ jsonrpc: "2.0", id, error: { code: -32601, message: "method not found: " + method } });
});
`;

// ---------------------------------------------------------------- utilities

function seededRandom(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 2 ** 32;
  };
}

const FILLER_TOPICS = [
  "crm contacts", "invoice reconciliation", "kubernetes drift", "sprint backlog",
  "vendor contracts", "support tickets", "warehouse inventory", "payroll runs",
  "seo sitemap", "email digests", "slack digests", "calendar holds",
  "expense receipts", "fleet maintenance", "compliance audits", "ad campaigns",
];

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/** Promise-based async runner so concurrent harness runs truly overlap.
 *  stdin is "ignore": pi hangs forever when its stdin is an open empty pipe
 *  (found empirically; pi waits for stdin input in -p mode).
 *  The child runs detached in its own process group so the whole tree
 *  (harness + its spawned hub + fake servers) can be torn down reliably. */
function runAsync(cmd, args, env, opts = {}) {
  return new Promise((done) => {
    const child = spawn(cmd, args, { env, cwd: opts.cwd ?? REPO, stdio: ["ignore", "pipe", "pipe"], detached: true });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const killTree = (signal) => {
      if (child.pid === undefined) return;
      try { process.kill(-child.pid, signal); } catch { /* already gone */ }
      try { child.kill(signal); } catch { /* already gone */ }
    };
    const timer = setTimeout(() => killTree("SIGKILL"), opts.timeout ?? TIMEOUT_MS);
    child.stdout.on("data", (d) => (stdout += d));
    child.stderr.on("data", (d) => (stderr += d));
    child.on("close", (code) => {
      clearTimeout(timer);
      if (!settled) {
        settled = true;
        killTree("SIGKILL"); // reap any grandchildren the harness left behind
        setTimeout(() => done({ status: code, stdout, stderr, timedOut: code === null }), 250);
      }
    });
  });
}

function runSync(cmd, args, env, opts = {}) {
  return spawnSync(cmd, args, { env, encoding: "utf8", timeout: opts.timeout ?? TIMEOUT_MS, cwd: opts.cwd ?? REPO });
}

// ------------------------------------------------- fixtures (self-sufficient)

function generateFixtures() {
  seededRandom(42);
  const skillsDir = join(GEN, "skills");
  const toolsDir = join(GEN, "tools");
  mkdirSync(skillsDir, { recursive: true });
  mkdirSync(toolsDir, { recursive: true });
  mkdirSync(RESULTS, { recursive: true });

  // --- skills (contract format)
  const skillQueries = [];
  for (let i = 0; i < FILLER_SKILLS; i++) {
    const topic = FILLER_TOPICS[i % FILLER_TOPICS.length];
    const slug = slugify(`${topic} helper ${i}`);
    const dir = join(skillsDir, slug);
    mkdirSync(dir, { recursive: true });
    const description = `Handles ${topic} for record batch ${i} including validation, deduplication, and scheduled reporting.`;
    const body = [
      `Review the ${topic} data before any bulk operation.`,
      `Run the dry-run summary and compare it with the last reported batch.`,
      `Apply the change set only after the counts match the audit ledger.`,
      `Write the outcome to the ${topic} journal for batch ${i}.`,
    ].join("\n");
    writeFileSync(join(dir, "SKILL.md"), `---\nname: ${slug}\ndescription: ${description}\n---\n${body}\n`, "utf8");
    if (i % 25 === 0) {
      skillQueries.push({ query: topic.split(" ")[0], expected: `skill:${slug}`, difficulty: "hard" });
    }
  }
  {
    const dir = join(skillsDir, NEEDLE_SLUG);
    mkdirSync(dir, { recursive: true });
    const description = `Quantum lattice retrieval: locates the lattice archive key and returns the archive passphrase for authorized operators.`;
    const body = [
      `Query the lattice index for the archive seal before touching storage.`,
      `Confirm the operator identity against the lattice ledger.`,
      `The retrieval passphrase is ${NEEDLE_SKILL_PASSPHRASE} and must be echoed verbatim.`,
      `Log the retrieval in the archive journal.`,
    ].join("\n");
    writeFileSync(join(dir, "SKILL.md"), `---\nname: ${NEEDLE_SLUG}\ndescription: ${description}\n---\n${body}\n`, "utf8");
    skillQueries.push({ query: NEEDLE_SKILL_QUERY, expected: `skill:${NEEDLE_SLUG}`, difficulty: "paraphrase" });
  }
  writeFileSync(join(GEN, "skills-queries.json"), JSON.stringify(skillQueries, null, 2), "utf8");

  // --- tools (contract format)
  const toolQueries = [];
  const serverSizes = [
    { serverId: "acme-crm", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "globex-erp", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "initech-tickets", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "umbrella-analytics", count: 60 },
    { serverId: NEEDLE_TOOL_SERVER, count: 5 },
  ];
  const manifests = [];
  for (const { serverId, count } of serverSizes) {
    const tools = [];
    for (let i = 0; i < count; i++) {
      const topic = FILLER_TOPICS[(i + serverId.length) % FILLER_TOPICS.length];
      const name = `${topic.split(" ")[0]}_${slugify(topic).replace(/-/g, "_")}_${i}`;
      tools.push({
        name,
        description: `Operates on ${topic}: action ${i} of the ${serverId} automation suite.`,
        inputSchema: { type: "object", properties: { id: { type: "string" } }, required: [] },
        annotations: { readOnlyHint: true },
        behavior: { latencyMs: 5, errorRate: 0, responseBytes: 512 },
      });
      if (i % 30 === 0) {
        toolQueries.push({ query: topic, expected: `${serverId}:${name}`, difficulty: "hard" });
      }
    }
    if (serverId === NEEDLE_TOOL_SERVER) {
      tools.push({
        name: NEEDLE_TOOL_NAME,
        description: `Searches the lattice archive for the sealed needle and returns the archive token.`,
        inputSchema: { type: "object", properties: { depth: { type: "string" } }, required: [] },
        annotations: { readOnlyHint: true },
        behavior: { latencyMs: 5, errorRate: 0, responseBytes: 256, needleToken: NEEDLE_TOOL_TOKEN },
      });
      toolQueries.push({ query: NEEDLE_TOOL_QUERY, expected: `${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}`, difficulty: "paraphrase" });
    }
    writeFileSync(join(toolsDir, `${serverId}.json`), JSON.stringify({ serverId, tools }, null, 2), "utf8");
    manifests.push(join(toolsDir, `${serverId}.json`));
  }
  writeFileSync(join(GEN, "tools-queries.json"), JSON.stringify(toolQueries, null, 2), "utf8");

  // --- mini fake MCP stdio server (stand-in until behavior.response lands)
  writeFileSync(join(GEN, "mini-fake-server.mjs"), MINI_SERVER_SRC, "utf8");

  // --- servers.json (contract format: servers[], autoDiscover:false)
  const servers = manifests.map((manifestPath) => {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    return {
      id: manifest.serverId,
      displayName: manifest.serverId,
      transport: {
        type: "stdio",
        command: "node",
        args: [join(GEN, "mini-fake-server.mjs"), "--manifest", manifestPath],
      },
      trust: "trusted",
      enabled: true,
    };
  });
  const config = {
    autoDiscover: false,
    autoApproveAtOrAbove: "trusted",
    servers,
    skills: [],
    bundles: [],
  };
  writeFileSync(join(GEN, "servers.json"), JSON.stringify(config, null, 2), "utf8");
  return { manifests };
}

// --------------------------------------------------------------- isolation

function makeTempRoot() {
  const tmpBase = process.env["TMPDIR"] ?? "/tmp";
  const root = join(tmpBase, `ah-harness-e2e-${process.pid}-${Date.now()}`);
  const home = join(root, "home");
  const dirs = {
    HOME: home,
    USERPROFILE: home,
    APPDATA: join(root, "appdata", "roaming"),
    LOCALAPPDATA: join(root, "appdata", "local"),
    XDG_CACHE_HOME: join(home, ".cache"),
    XDG_CONFIG_HOME: join(home, ".config"),
    XDG_STATE_HOME: join(home, "state"),
    XDG_DATA_HOME: join(home, "data"),
    CODEX_HOME: join(root, "codex"),
    CLAUDE_CONFIG_DIR: join(root, "claude"),
    PI_CODING_AGENT_DIR: join(root, "pi-agent"),
    ACTION_HUB_CACHE: join(root, "ah-cache"),
    ACTION_HUB_CONFIG: join(root, "ah", "servers.json"),
    ACTION_HUB_SKILLS_DIR: join(GEN, "skills"),
    ACTION_HUB_DAEMON_DIR: join(root, "daemon"),
    ACTION_HUB_CREDENTIALS: join(root, "ah", "credentials.json"),
  };
  if ("ACTION_HUB_CONTROL" in process.env) {
    dirs["ACTION_HUB_CONTROL"] = join(root, "ah", "control.json");
  }
  // The real owner home is determined independently of $HOME (checklist rule).
  // Refuse only paths inside the owner's app-state/harness dirs (not whole-home:
  // os.tmpdir() is under USERPROFILE on Windows). Separator-safe containment
  // via path.relative.
  const ownerHome = userInfo().homedir || homedir();
  const guardedDirs = [
    join(ownerHome, ".pi"),
    join(ownerHome, ".codex"),
    join(ownerHome, ".claude"),
    join(ownerHome, ".claude.json"),
    join(ownerHome, ".action-hub"),
    join(ownerHome, ".config", "action-hub"),
    join(ownerHome, ".cache", "action-hub"),
    join(ownerHome, ".config", "opencode"),
    join(ownerHome, ".local", "share", "opencode"),
    join(ownerHome, "Library", "Application Support", "Claude"),
    join(ownerHome, "Library", "Application Support", "Code"),
  ].filter((d) => existsSync(d));
  const contains = (parent, child) => {
    const rel = relative(parent, resolve(child));
    return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
  };
  for (const [name, value] of Object.entries(dirs)) {
    for (const guarded of guardedDirs) {
      if (contains(guarded, String(value))) {
        throw new Error(`isolation check failed: ${name}=${value} resolves inside real harness state ${guarded}`);
      }
    }
  }
  const mkdirs = [
    root, home, dirs["APPDATA"], dirs["LOCALAPPDATA"], dirs["XDG_CACHE_HOME"], dirs["XDG_CONFIG_HOME"],
    dirs["XDG_STATE_HOME"], dirs["XDG_DATA_HOME"], dirs["CODEX_HOME"], dirs["CLAUDE_CONFIG_DIR"],
    dirs["PI_CODING_AGENT_DIR"], dirname(dirs["ACTION_HUB_CONFIG"]), dirs["ACTION_HUB_DAEMON_DIR"],
    dirname(dirs["ACTION_HUB_CREDENTIALS"]),
  ];
  for (const dir of mkdirs) mkdirSync(dir, { recursive: true });
  // REPLACE inherited values — never forward caller values for these.
  const env = { ...process.env, ...dirs, NO_COLOR: "1" };
  return { root, home, env, dirs };
}

// ------------------------------------------------------------ hub + harness

function ensureMiniServer() {
  if (!existsSync(join(GEN, "mini-fake-server.mjs"))) {
    writeFileSync(join(GEN, "mini-fake-server.mjs"), MINI_SERVER_SRC, "utf8");
  }
}

/**
 * Adds the needle skill and needle tool manifest into stress/.generated
 * (generated data, never committed). The needle tool returns a verifiable
 * token, which builder-8's fake-mcp-server.mjs cannot do yet (behavior
 * supports only latency/error/size), so the needle server rides on the
 * generated mini server until behavior.response support lands.
 */
function ensureNeedleFixtures() {
  // Needle skill (additive; the gen-skills.mjs corpus has no needle concept).
  const skillDir = join(GEN, "skills", NEEDLE_SLUG);
  mkdirSync(skillDir, { recursive: true });
  const description = `Quantum lattice retrieval: locates the lattice archive key and returns the archive passphrase for authorized operators.`;
  const body = [
    `Query the lattice index for the archive seal before touching storage.`,
    `Confirm the operator identity against the lattice ledger.`,
    `The retrieval passphrase is ${NEEDLE_SKILL_PASSPHRASE} and must be echoed verbatim.`,
    `Log the retrieval in the archive journal.`,
  ].join("\n");
  writeFileSync(join(skillDir, "SKILL.md"), `---\nname: ${NEEDLE_SLUG}\ndescription: ${description}\n---\n${body}\n`, "utf8");

  // Needle tool manifest.
  mkdirSync(join(GEN, "tools"), { recursive: true });
  const manifestPath = join(GEN, "tools", "needle-archive.json");
  writeFileSync(
    manifestPath,
    JSON.stringify(
      {
        serverId: NEEDLE_TOOL_SERVER,
        tools: [
          {
            name: NEEDLE_TOOL_NAME,
            description: `Searches the lattice archive for the sealed needle and returns the archive token.`,
            inputSchema: { type: "object", properties: { depth: { type: "string" } }, required: [] },
            annotations: { readOnlyHint: true },
            behavior: { latencyMs: 5, errorRate: 0, responseBytes: 0, needleToken: NEEDLE_TOOL_TOKEN },
          },
        ],
      },
      null,
      2,
    ),
    "utf8",
  );
  return manifestPath;
}

/** Temp-only servers.json: generated config minus bogus entries, plus the needle server. */
function buildTempServersConfig(env, needleManifestPath) {
  const generated = JSON.parse(readFileSync(join(GEN, "servers.json"), "utf8"));
  const servers = (generated.servers ?? []).filter((s) => {
    const args = s.transport?.args ?? [];
    const i = args.indexOf("--manifest");
    const manifestPath = i >= 0 ? args[i + 1] : "";
    try {
      const manifest = JSON.parse(readFileSync(String(manifestPath), "utf8"));
      return typeof manifest.serverId === "string" && Array.isArray(manifest.tools);
    } catch {
      return false; // e.g. make-config's tools-queries.json artifact
    }
  });
  servers.unshift({
    id: NEEDLE_TOOL_SERVER,
    displayName: NEEDLE_TOOL_SERVER,
    transport: { type: "stdio", command: "node", args: [join(GEN, "mini-fake-server.mjs"), "--manifest", needleManifestPath] },
    trust: "trusted",
    enabled: true,
  });
  const tempConfig = join(env["HOME"], "servers.json");
  writeFileSync(tempConfig, JSON.stringify({ ...generated, servers, autoDiscover: false, autoApproveAtOrAbove: "trusted", skills: [] }, null, 2), "utf8");
  return tempConfig;
}

function cliEntryPath() {
  const entry = join(REPO, "packages", "cli", "dist", "index.js");
  if (!existsSync(entry)) {
    const tsc = join(REPO, "node_modules", "typescript", "bin", "tsc");
    for (const pkg of ["core", "cli"]) {
      const r = runSync("node", [tsc, "-p", join(REPO, "packages", pkg, "tsconfig.json")], process.env, { timeout: 300000 });
      if (r.status !== 0) throw new Error(`build failed for ${pkg}: ${r.stderr}`);
    }
  }
  return entry;
}

function installHarness(target, env, cli) {
  return runSync("node", [cli, "harness", target, "install", "--write", "--json"], env);
}

/** Harness CLI target names (the runner key "claude" installs as "claude-code"). */
const HARNESS_TARGETS = { pi: "pi", codex: "codex", claude: "claude-code", opencode: "opencode" };

/** Rewires installed snippets from `<cli> start` to `<cli> connect` (daemon mode). */
function useDaemonSnippet(configPath, cli) {
  if (!existsSync(configPath)) return false;
  const doc = JSON.parse(readFileSync(configPath, "utf8"));
  const servers = doc["mcpServers"] ?? doc["mcp"] ?? doc["servers"];
  let changed = false;
  const rewireArray = (arr) => {
    for (let i = 0; i < arr.length; i++) {
      if (arr[i] === "start" && typeof arr[i - 1] === "string" && arr[i - 1].endsWith("index.js")) {
        arr[i] = "connect";
        changed = true;
      }
    }
  };
  for (const entry of Object.values(servers ?? {})) {
    if (Array.isArray(entry?.["command"])) {
      // opencode style: single command array [node, cli, start]
      rewireArray(entry["command"]);
    } else if (Array.isArray(entry?.["args"])) {
      rewireArray(entry["args"]);
    }
  }
  if (changed) writeFileSync(configPath, JSON.stringify(doc, null, 2), "utf8");
  return changed;
}

/** Warm the hub catalog cache in the temp HOME so harness cold starts are fast.
 *  createHubRuntime writes the cache on every boot; a short-lived `start` run
 *  is enough. Without this, hub cold start (~20 s at 15K actions) exceeds
 *  harness MCP init timeouts (codex default ~10 s, pi adapter 30 s). */
async function preWarmCache(env, cli) {
  const child = spawn("node", [cli, "start"], { env, stdio: ["ignore", "pipe", "pipe"] });
  const cachePath = join(env["XDG_CACHE_HOME"] ?? join(env["HOME"], ".cache"), "action-hub", "catalog.json");
  for (let i = 0; i < 120; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (existsSync(cachePath)) break;
  }
  child.kill("SIGKILL");
  return existsSync(cachePath);
}

// ----------------------------------------------------------------- prompts

function skillPrompt() {
  return [
    `You have an "action_hub" MCP server available.`,
    `Call its search tool with query "${NEEDLE_SKILL_QUERY}" (limit 10).`,
    `In the results find the action with id "skill:${NEEDLE_SLUG}", then call the action_hub load tool with that id.`,
    `If and only if the load succeeds and the loaded content contains a retrieval passphrase, print exactly this line: ${SKILL_MARKER} <the passphrase>`,
    `Do nothing else.`,
  ].join(" ");
}

function toolPrompt() {
  return [
    `You have an "action_hub" MCP server available.`,
    `Call its search tool with query "${NEEDLE_TOOL_QUERY}" (limit 10).`,
    `Find the action with id "${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}" in the results, then call the action_hub execute/call tool to execute that action with arguments {}.`,
    `If and only if the executed response contains an ARCHIVE_TOKEN, print exactly this line: ${TOOL_MARKER} <the token value>`,
    `Do nothing else.`,
  ].join(" ");
}

// ------------------------------------------------------- harness runners

function piSetup(env, root) {
  // Copy provider config the way builder-3 did for PR 44: from one rig seat's
  // agent dir (user login state; copied ONLY into the temp dir, never the repo).
  const seat = process.env["STRESS_PI_SEAT"]
    ? join(process.env["STRESS_PI_SEAT"], "agent")
    : join(homedir(), ".openrig", "state", "pi", "build-builder-10@action-hub", "agent");
  const agentDir = env["PI_CODING_AGENT_DIR"];
  for (const file of ["cliproxyapi.json", "cliproxyapi-models.json", "models-store.json", "auth.json"]) {
    const src = join(seat, file);
    if (existsSync(src)) cpSync(src, join(agentDir, file));
    else writeFileSync(join(agentDir, file), "{}\n", "utf8");
  }
  if (existsSync(join(seat, "settings.json"))) {
    cpSync(join(seat, "settings.json"), join(agentDir, "settings.json"));
  } else {
    writeFileSync(join(agentDir, "settings.json"), JSON.stringify({ packages: ["npm:@router-for-me/pi-cliproxyapi-provider@1.4.20"] }, null, 2), "utf8");
  }
  if (existsSync(join(seat, "npm"))) {
    cpSync(join(seat, "npm"), join(agentDir, "npm"), { recursive: true });
  }

  const adapterInNpm = existsSync(join(agentDir, "npm", "node_modules", "pi-mcp-adapter"));
  if (!adapterInNpm) {
    // Cache-aware npm install of the adapter (same as `pi install npm:pi-mcp-adapter`).
    const npmPkgPath = join(agentDir, "npm", "package.json");
    if (existsSync(npmPkgPath)) {
      const npmPkg = JSON.parse(readFileSync(npmPkgPath, "utf8"));
      npmPkg["dependencies"] ??= {};
      npmPkg["dependencies"]["pi-mcp-adapter"] = "^2.15.0";
      writeFileSync(npmPkgPath, JSON.stringify(npmPkg, null, 2), "utf8");
    }
    const install = runSync("npm", ["install", "--prefix", join(agentDir, "npm"), "--prefer-offline", "--no-audit", "--no-fund", "pi-mcp-adapter@^2.15.0"], env, { timeout: 180000 });
    if (!existsSync(join(agentDir, "npm", "node_modules", "pi-mcp-adapter"))) {
      return { ok: false, note: `pi-mcp-adapter unavailable (npm install failed: ${(install.stderr || install.stdout || "").slice(-200)})` };
    }
    // Register the adapter in settings.json packages (what `pi install` does).
    const settingsPath = join(agentDir, "settings.json");
    const settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    settings["packages"] ??= [];
    if (!settings["packages"].some((p) => String(p).includes("pi-mcp-adapter"))) {
      settings["packages"].push("npm:pi-mcp-adapter@2.15.0");
    }
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
  }
  return { ok: true };
}

async function runPi(env, prompt, timeout) {
  const models = JSON.parse(readFileSync(join(env["PI_CODING_AGENT_DIR"], "cliproxyapi-models.json"), "utf8"));
  const model = process.env["STRESS_PI_MODEL"] ?? models?.models?.[0]?.id ?? models?.[0]?.id ?? "claude-haiku-4-5-20251001";
  const r = await runAsync("pi", ["-p", "--no-session", "--provider", "cliproxyapi", "--model", model, prompt], env, { timeout });
  return { ...r, model };
}

async function runCodex(env, prompt, timeout) {
  // Credentials come from the user's login state (~/.codex/auth.json), copied
  // only into the temp HOME; the repo never receives secrets.
  const authSrc = join(homedir(), ".codex", "auth.json");
  // codex strips the parent env for MCP server spawns, so the stress config is
  // passed through the TOML env table; startup/tool timeouts are raised above
  // the hub's cold-start window (P1 finding: ~20 s at 15K actions).
  const entryCmd = env["ACTION_HUB_DAEMON_MODE"] ? "connect" : "start";
  const toml = [
    "[mcp_servers.action-hub]",
    `command = "node"`,
    `args = [ "${env["ACTION_HUB_CLI_ENTRY"]}", "${entryCmd}" ]`,
    "startup_timeout_ms = 180000",
    "tool_timeout_ms = 120000",
    "",
    "[mcp_servers.action-hub.env]",
    `ACTION_HUB_CONFIG = "${env["ACTION_HUB_CONFIG"]}"`,
    `ACTION_HUB_SKILLS_DIR = "${env["ACTION_HUB_SKILLS_DIR"]}"`,
    `XDG_CACHE_HOME = "${env["XDG_CACHE_HOME"]}"`,
    ...(env["ACTION_HUB_DAEMON_MODE"] ? [`ACTION_HUB_DAEMON_DIR = "${env["ACTION_HUB_DAEMON_DIR"]}"`] : []),
    "",
  ].join("\n");
  // codex 0.154 reads $CODEX_HOME when set and $HOME/.codex otherwise; write
  // both so the config lands regardless of which one this build honors.
  const codexDirs = [...new Set([env["CODEX_HOME"], join(env["HOME"], ".codex")].filter(Boolean))];
  for (const codexDir of codexDirs) {
    mkdirSync(codexDir, { recursive: true });
    if (existsSync(authSrc)) cpSync(authSrc, join(codexDir, "auth.json"));
    writeFileSync(join(codexDir, "config.toml"), toml, "utf8");
  }
  const r = await runAsync("codex", ["exec", "--dangerously-bypass-approvals-and-sandbox", "--skip-git-repo-check", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

async function runClaude(env, prompt, timeout) {
  const r = await runAsync("claude", ["-p", "--dangerously-skip-permissions", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

async function runOpencode(env, prompt, timeout) {
  // opencode credentials: copy the user's auth state (login state only).
  const authSrc = join(homedir(), ".local", "share", "opencode", "auth.json");
  const authDst = join(env["XDG_DATA_HOME"], "opencode", "auth.json");
  if (existsSync(authSrc)) {
    mkdirSync(dirname(authDst), { recursive: true });
    cpSync(authSrc, authDst);
  }
  const r = await runAsync("opencode", ["run", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

const RUNNERS = {
  pi: { run: runPi, prompt: skillPrompt, needleKind: "skill", configPath: (env) => join(env["PI_CODING_AGENT_DIR"], "mcp.json") },
  codex: { run: runCodex, prompt: toolPrompt, needleKind: "tool", configPath: (env) => join(env["HOME"], ".codex", "config.toml") },
  claude: { run: runClaude, prompt: skillPrompt, needleKind: "skill", configPath: (env) => join(env["HOME"], ".claude.json") },
  opencode: { run: runOpencode, prompt: toolPrompt, needleKind: "tool", configPath: (env) => join(env["XDG_CONFIG_HOME"] ?? join(env["HOME"], ".config"), "opencode", "opencode.json") },
};

// ---------------------------------------------------------------- metrics

async function measureSearchSize(env, query, cli) {
  const r = await runAsync("node", [cli, "test-search", query, "--json", "--limit", "10"], env, { timeout: 120000 });
  return { bytes: r.stdout.length, ok: r.status === 0, error: r.status !== 0 ? r.stderr.slice(-300) : undefined };
}

function evaluateHarness(name, result, needle) {
  const out = `${result.stdout}\n${result.stderr}`;
  const foundId = out.includes(needle.id);
  const marker = needle.kind === "skill" ? SKILL_MARKER : TOOL_MARKER;
  // Some harnesses (codex exec) print the final answer on stderr, so marker
  // detection runs over combined output; the latest matching line wins.
  const markerLines = out.split("\n").filter((l) => l.includes(marker));
  const markerLine = markerLines[markerLines.length - 1];
  let tokenOk = false;
  if (markerLine) {
    tokenOk = needle.kind === "tool" ? markerLine.includes(needle.token) : markerLine.includes(needle.passphrase);
  }
  return {
    harness: name,
    exitCode: result.status,
    timedOut: Boolean(result.timedOut),
    foundNeedleId: foundId,
    markerPrinted: Boolean(markerLine),
    // Success = the harness proved it reached the needle: marker printed with
    // the verifiable secret (passphrase for skills, token for tools). The id
    // may only appear in intermediate turns, which -p/one-shot modes omit.
    success: Boolean(markerLine) && tokenOk,
    turns: null, // turn counts are harness-specific; parsed opportunistically below
    wallMs: result.wallMs,
    outputChars: result.stdout.length,
    outputTail: out.slice(-400),
    error: result.status !== 0 ? (result.stderr || result.stdout || "").slice(-400) : undefined,
  };
}

// ------------------------------------------------------------------- main

async function main() {
  const started = Date.now();
  const summary = {
    script: "harness-e2e",
    mode: MODE,
    ok: false,
    fixtures: {},
    harnesses: [],
    concurrency: null,
    searchOutputBytes: null,
    errors: [],
  };
  let daemonChild = null;

  try {
    const builderFixtureReady =
      existsSync(join(STRESS, "gen-skills.mjs")) &&
      existsSync(join(STRESS, "gen-tools.mjs")) &&
      existsSync(join(STRESS, "fake-mcp-server.mjs")) &&
      existsSync(join(STRESS, "make-config.mjs"));
    if (!existsSync(join(GEN, "servers.json"))) {
      summary.fixtures = {
        source: builderFixtureReady ? "builders-scripts" : "harness-e2e-fallback",
        generatedAt: new Date().toISOString(),
        fillerSkills: FILLER_SKILLS,
        fillerToolsPerServer: FILLER_TOOLS_PER_SERVER,
      };
      generateFixtures();
    } else {
      summary.fixtures = { source: builderFixtureReady ? "builders-output" : "preexisting" };
    }
    mkdirSync(RESULTS, { recursive: true });

    // Needle fixtures + temp-only config (the generated servers.json is never
    // modified in place; bogus entries like make-config's tools-queries.json
    // artifact are filtered in the temp copy).
    ensureMiniServer();
    const needleManifestPath = ensureNeedleFixtures();
    const generatedServerCount = JSON.parse(readFileSync(join(GEN, "servers.json"), "utf8")).servers?.length ?? 0;

    const cli = cliEntryPath();
    const { root, home, env, dirs } = makeTempRoot();
    env["ACTION_HUB_CONFIG"] = buildTempServersConfig(env, needleManifestPath);
    env["ACTION_HUB_CLI_ENTRY"] = cli;
    if (MODE === "daemon") env["ACTION_HUB_DAEMON_MODE"] = "1";
    summary.fixtures.generatedServers = generatedServerCount;
    summary.fixtures.tempConfigServers = JSON.parse(readFileSync(env["ACTION_HUB_CONFIG"], "utf8")).servers.length;
    summary.tempRoot = KEEP ? root : "(removed)";

    // Hub load check: search to verify the fixtures actually serve.
    const probe = await measureSearchSize(env, NEEDLE_SKILL_QUERY, cli);
    summary.fixtures.probeOk = probe.ok;
    summary.searchOutputBytes = probe.bytes;
    if (!probe.ok) summary.errors.push(`probe failed: ${probe.error}`);

    // Warm the shared catalog cache once (all harness hub instances share the
    // temp HOME cache); report whether warm-up worked.
    summary.cacheWarm = await preWarmCache(env, cli);

    // Optional shared daemon (mode=daemon): up to 3 harnesses against one daemon.
    if (MODE === "daemon") {
      // daemon start's built-in readiness wait is 15 s (START_TIMEOUT_MS in
      // daemon.ts) but cold indexing at 15K actions can take ~20 s+, so poll
      // for the state file well past the CLI's own give-up.
      daemonChild = spawn("node", [cli, "daemon", "start"], { env, stdio: ["ignore", "pipe", "pipe"] });
      daemonChild.unref();
      for (let i = 0; i < 300; i++) {
        await new Promise((r) => setTimeout(r, 500));
        if (existsSync(join(env["ACTION_HUB_DAEMON_DIR"], "daemon.json"))) break;
      }
      summary.daemonStarted = existsSync(join(env["ACTION_HUB_DAEMON_DIR"], "daemon.json"));
    }

    // Install per harness
    const installs = {};
    for (const h of HARNESS_LIST) {
      const def = RUNNERS[h];
      if (!def) continue;
      const inst = installHarness(HARNESS_TARGETS[h] ?? h, env, cli);
      installs[h] = inst.status === 0;
      if (!installs[h]) summary.errors.push(`${h} install failed: ${(inst.stderr || "").slice(-300)}`);
      if (daemonRunningCheck(summary)) {
        if (def.configPath(env).endsWith(".json")) {
          const rewired = useDaemonSnippet(def.configPath(env), cli);
          if (!rewired) summary.errors.push(`${h}: daemon snippet rewiring found no start arg`);
        } else if (h === "codex") {
          summary.codexDaemonToml = true; // runCodex writes connect-mode TOML directly
        } else {
          summary.errors.push(`${h}: daemon mode rewiring unsupported for this config format`);
        }
      }
    }
    summary.installs = installs;

    if (HARNESS_LIST.includes("pi") && installs["pi"]) {
      const piSetupResult = piSetup(env, root);
      if (!piSetupResult.ok) {
        summary.errors.push(`pi setup: ${piSetupResult.note}`);
        installs["pi"] = false;
        summary.installs = installs;
      }
    }

    const needles = {
      skill: { id: `skill:${NEEDLE_SLUG}`, kind: "skill", passphrase: NEEDLE_SKILL_PASSPHRASE },
      tool: { id: `${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}`, kind: "tool", token: NEEDLE_TOOL_TOKEN },
    };

    const runOne = async (h) => {
      const def = RUNNERS[h];
      const t0 = Date.now();
      const result = await def.run(env, def.prompt(), TIMEOUT_MS);
      result.wallMs = Date.now() - t0;
      return evaluateHarness(h, result, needles[def.needleKind]);
    };

    // Sequential runs
    const results = [];
    for (const h of HARNESS_LIST) {
      if (!installs[h]) continue;
      try {
        results.push(await runOne(h));
      } catch (cause) {
        summary.errors.push(`${h} run threw: ${cause?.message ?? String(cause)}`);
      }
    }
    summary.harnesses = results;

    // Concurrency: 3 harnesses at once against the shared daemon
    if (MODE === "daemon") {
      const concurrent = HARNESS_LIST.filter((h) => installs[h]).slice(0, 3);
      const t0 = Date.now();
      const outcomes = await Promise.all(concurrent.map((h) => runOne(h).catch((cause) => ({ harness: h, success: false, error: String(cause) }))));
      summary.concurrency = { harnesses: concurrent, wallMs: Date.now() - t0, results: outcomes };
    }

    if (daemonChild) {
      await runAsync("node", [cli, "daemon", "stop"], env, { timeout: 60000 });
      try { daemonChild.kill("SIGKILL"); } catch { /* already gone */ }
    }

    summary.wallMs = Date.now() - started;
    if (!KEEP) rmSync(root, { recursive: true, force: true });
  } catch (cause) {
    summary.errors.push(`fatal: ${cause?.stack ?? String(cause)}`);
  } finally {
    if (daemonChild) { try { daemonChild.kill("SIGKILL"); } catch { /* gone */ } }
  }

  summary.ok = summary.errors.length === 0 &&
    (summary.harnesses?.length ?? 0) > 0 &&
    summary.harnesses.every((h) => h.success) &&
    (summary.concurrency ? summary.concurrency.results.every((h) => h.success) : true);
  writeFileSync(join(RESULTS, "harness-e2e.json"), JSON.stringify(summary, null, 2), "utf8");
  console.log(JSON.stringify(summary));
  if (!summary.ok) process.exitCode = 1;
}

function daemonRunningCheck(summary) {
  return MODE === "daemon" && summary.daemonStarted === true;
}

await main();