#!/usr/bin/env node
/**
 * stress/harness-e2e.mjs — S7: real harness CLIs against the stress Action Hub.
 *
 * Owner: builder-9. Binding contract: /tmp/action-hub-stress/CONTRACT.md.
 *
 * Fully isolated: every run uses a temp HOME / XDG dirs / ACTION_HUB_CONFIG /
 * ACTION_HUB_SKILLS_DIR / PI_CODING_AGENT_DIR. The user's real ~/.pi, ~/.codex,
 * ~/.claude, and opencode configs are never modified; harness credentials come
 * from the user's login state copied ONLY into the run's temp directory (never
 * committed, never written back).
 *
 * What it does:
 *   1. Builds fixtures if stress/.generated is not populated yet (deterministic,
 *      seeded, contract format: skills/<slug>/SKILL.md, tools/<serverId>.json,
 *      servers.json with autoDiscover:false). When builder-1/-4/-2 generators
 *      exist and have produced .generated, their outputs are used as-is.
 *   2. Installs the stress hub into each real harness CLI via
 *      `action-hub harness <target> install --write` (temp config locations).
 *   3. Asks each harness (pi -p, codex exec, claude -p, opencode run) to find a
 *      needle action among the catalog, load/execute it, and print a marker.
 *   4. Measures per harness: needle found + loaded, wall time, search output
 *      size (context fit), and emits a machine-readable JSON summary (last
 *      stdout line + stress/.generated/results/harness-e2e.json).
 *   5. --mode daemon: 3 harnesses run concurrently against ONE shared daemon.
 *
 * Usage:
 *   node stress/harness-e2e.mjs [--harnesses pi,codex,claude,opencode]
 *        [--mode standalone|daemon] [--filler-skills N] [--filler-tools N]
 *        [--timeout secs] [--keep]
 */

import { spawn } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir, userInfo } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const argv = process.argv.slice(2);
function arg(name, fallback) {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && argv[i + 1] !== undefined ? argv[i + 1] : fallback;
}
const flag = (name) => argv.includes(`--${name}`);

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STRESS = join(REPO, "stress");
const GEN = join(STRESS, ".generated");
const RESULTS = join(GEN, "results");
const TIMEOUT_MS = Number(arg("timeout", "240")) * 1000;
const HARNESS_LIST = String(arg("harnesses", "pi,codex,claude,opencode")).split(",");
const MODE = String(arg("mode", "standalone"));
// Fault injection for the self-test: --fault daemon-start sabotages the daemon
// spawn (state dir parent is a file -> state write must fail) to prove a daemon
// failure gates ok:false with one failure JSON and a nonzero exit.
const FAULT = String(arg("fault", "none"));
const KEEP = flag("keep");
const FILLER_SKILLS = Number(arg("filler-skills", "150"));
const FILLER_TOOLS_PER_SERVER = Number(arg("filler-tools", "80"));

const NEEDLE_SLUG = "needle-quantum-lattice";
const NEEDLE_SKILL_PASSPHRASE = "LATTICE-PASSPHRASE-7K3F-Q9";
const NEEDLE_TOOL_SERVER = "needle-archive";
const NEEDLE_TOOL_NAME = "find_needle_lattice";
const NEEDLE_TOOL_TOKEN = "NEEDLE-TOKEN-A9F2-LATTICE";
const NEEDLE_SKILL_QUERY = "quantum lattice archive retrieval passphrase";
const NEEDLE_TOOL_QUERY = "lattice archive needle finder";
const SKILL_MARKER = "NEEDLE-SKILL-OK";
const TOOL_MARKER = "NEEDLE-TOOL-OK";

/** Stand-in fake MCP stdio server (supports the needleToken behavior). */
const MINI_SERVER_SRC = `#!/usr/bin/env node
// GENERATED by stress/harness-e2e.mjs (stand-in for fake-mcp-server.mjs). Do not edit.
import { createInterface } from "node:readline";
import { readFileSync } from "node:fs";
const manifestPath = process.argv[process.argv.indexOf("--manifest") + 1];
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const rl = createInterface({ input: process.stdin });
function send(msg) { process.stdout.write(JSON.stringify(msg) + "\\n"); }
rl.on("line", (line) => {
  if (!line.trim()) return;
  let req; try { req = JSON.parse(line); } catch { return; }
  const { id, method, params } = req;
  if (method === "initialize") return send({ jsonrpc: "2.0", id, result: { protocolVersion: params?.protocolVersion ?? "2025-06-18", capabilities: { tools: {} }, serverInfo: { name: manifest.serverId, version: "1.0.0" } } });
  if (method === "notifications/initialized") return;
  if (method === "tools/list") return send({ jsonrpc: "2.0", id, result: { tools: manifest.tools.map((t) => ({ name: t.name, description: t.description, inputSchema: t.inputSchema, annotations: t.annotations })) } });
  if (method === "tools/call") {
    const tool = manifest.tools.find((t) => t.name === params?.name);
    if (!tool) return send({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: "unknown tool" }], isError: true } });
    const needle = tool.behavior?.needleToken ? "\\nARCHIVE_TOKEN: " + tool.behavior.needleToken + "\\n" : "";
    return send({ jsonrpc: "2.0", id, result: { content: [{ type: "text", text: "ok " + tool.name + needle }] } });
  }
  send({ jsonrpc: "2.0", id, error: { code: -32601, message: "method not found: " + method } });
});
`;

// Create output dirs before ANY logic can fail, so every failure path can
// write the result file + last-line JSON (clean-clone has no .generated yet).
mkdirSync(GEN, { recursive: true });
mkdirSync(RESULTS, { recursive: true });

// ---------------------------------------------------------------- utilities

function seededRandom(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 2 ** 32;
  };
}

const FILLER_TOPICS = [
  "crm contacts", "invoice reconciliation", "kubernetes drift", "sprint backlog",
  "vendor contracts", "support tickets", "warehouse inventory", "payroll runs",
  "seo sitemap", "email digests", "slack digests", "calendar holds",
  "expense receipts", "fleet maintenance", "compliance audits", "ad campaigns",
];

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/** Promise-based async runner so concurrent harness runs truly overlap.
 *  stdin is "ignore": pi hangs forever when its stdin is an open empty pipe
 *  (found empirically; pi waits for stdin input in -p mode).
 *  The child runs detached in its own process group so the whole tree
 *  (harness + its spawned hub + fake servers) can be torn down reliably. */
function runAsync(cmd, args, env, opts = {}) {
  return new Promise((done) => {
    const child = spawn(cmd, args, { env, cwd: opts.cwd ?? REPO, stdio: ["ignore", "pipe", "pipe"], detached: true });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const killTreeChild = (signal) => killTree(child.pid, signal);
    let timedOut = false;
    const timer = setTimeout(() => { timedOut = true; killTree(child.pid, "SIGKILL"); }, opts.timeout ?? TIMEOUT_MS);
    child.stdout.on("data", (d) => (stdout += d));
    child.stderr.on("data", (d) => (stderr += d));
    child.on("error", (cause) => {
      // spawn/ENOENT etc: settle so the last-line JSON is always emitted.
      clearTimeout(timer);
      if (!settled) {
        settled = true;
        stderr += `\nspawn error: ${cause?.message ?? String(cause)}`;
        done({ status: null, stdout, stderr, timedOut, spawnError: cause?.code ?? String(cause) });
      }
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (!settled) {
        settled = true;
        killTreeChild("SIGKILL"); // reap any grandchildren the harness left behind
        void (async () => {
          if (child.pid !== undefined) await waitGone(child.pid, 3000);
          done({ status: code, stdout, stderr, timedOut });
        })();
      }
    });
  });
}

// ------------------------------------------------- fixtures (self-sufficient)

function generateFixtures() {
  seededRandom(42);
  const skillsDir = join(GEN, "skills");
  const toolsDir = join(GEN, "tools");
  mkdirSync(skillsDir, { recursive: true });
  mkdirSync(toolsDir, { recursive: true });
  mkdirSync(RESULTS, { recursive: true });

  // --- skills (contract format)
  const skillQueries = [];
  for (let i = 0; i < FILLER_SKILLS; i++) {
    const topic = FILLER_TOPICS[i % FILLER_TOPICS.length];
    const slug = slugify(`${topic} helper ${i}`);
    const dir = join(skillsDir, slug);
    mkdirSync(dir, { recursive: true });
    const description = `Handles ${topic} for record batch ${i} including validation, deduplication, and scheduled reporting.`;
    const body = [
      `Review the ${topic} data before any bulk operation.`,
      `Run the dry-run summary and compare it with the last reported batch.`,
      `Apply the change set only after the counts match the audit ledger.`,
      `Write the outcome to the ${topic} journal for batch ${i}.`,
    ].join("\n");
    writeFileSync(join(dir, "SKILL.md"), `---\nname: ${slug}\ndescription: ${description}\n---\n${body}\n`, "utf8");
    if (i % 25 === 0) {
      skillQueries.push({ query: topic.split(" ")[0], expected: `skill:${slug}`, difficulty: "hard" });
    }
  }
  {
    const dir = join(skillsDir, NEEDLE_SLUG);
    mkdirSync(dir, { recursive: true });
    const description = `Quantum lattice retrieval: locates the lattice archive key and returns the archive passphrase for authorized operators.`;
    const body = [
      `Query the lattice index for the archive seal before touching storage.`,
      `Confirm the operator identity against the lattice ledger.`,
      `The retrieval passphrase is ${NEEDLE_SKILL_PASSPHRASE} and must be echoed verbatim.`,
      `Log the retrieval in the archive journal.`,
    ].join("\n");
    writeFileSync(join(dir, "SKILL.md"), `---\nname: ${NEEDLE_SLUG}\ndescription: ${description}\n---\n${body}\n`, "utf8");
    skillQueries.push({ query: NEEDLE_SKILL_QUERY, expected: `skill:${NEEDLE_SLUG}`, difficulty: "paraphrase" });
  }
  writeFileSync(join(GEN, "skills-queries.json"), JSON.stringify(skillQueries, null, 2), "utf8");

  // --- tools (contract format)
  const toolQueries = [];
  const serverSizes = [
    { serverId: "acme-crm", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "globex-erp", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "initech-tickets", count: FILLER_TOOLS_PER_SERVER },
    { serverId: "umbrella-analytics", count: 60 },
    { serverId: NEEDLE_TOOL_SERVER, count: 5 },
  ];
  const manifests = [];
  for (const { serverId, count } of serverSizes) {
    const tools = [];
    for (let i = 0; i < count; i++) {
      const topic = FILLER_TOPICS[(i + serverId.length) % FILLER_TOPICS.length];
      const name = `${topic.split(" ")[0]}_${slugify(topic).replace(/-/g, "_")}_${i}`;
      tools.push({
        name,
        description: `Operates on ${topic}: action ${i} of the ${serverId} automation suite.`,
        inputSchema: { type: "object", properties: { id: { type: "string" } }, required: [] },
        annotations: { readOnlyHint: true },
        behavior: { latencyMs: 5, errorRate: 0, responseBytes: 512 },
      });
      if (i % 30 === 0) {
        toolQueries.push({ query: topic, expected: `${serverId}:${name}`, difficulty: "hard" });
      }
    }
    if (serverId === NEEDLE_TOOL_SERVER) {
      tools.push({
        name: NEEDLE_TOOL_NAME,
        description: `Searches the lattice archive for the sealed needle and returns the archive token.`,
        inputSchema: { type: "object", properties: { depth: { type: "string" } }, required: [] },
        annotations: { readOnlyHint: true },
        behavior: { latencyMs: 5, errorRate: 0, responseBytes: 256, needleToken: NEEDLE_TOOL_TOKEN },
      });
      toolQueries.push({ query: NEEDLE_TOOL_QUERY, expected: `${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}`, difficulty: "paraphrase" });
    }
    writeFileSync(join(toolsDir, `${serverId}.json`), JSON.stringify({ serverId, tools }, null, 2), "utf8");
    manifests.push(join(toolsDir, `${serverId}.json`));
  }
  writeFileSync(join(GEN, "tools-queries.json"), JSON.stringify(toolQueries, null, 2), "utf8");

  // --- mini fake MCP stdio server (stand-in until behavior.response lands)
  writeFileSync(join(GEN, "mini-fake-server.mjs"), MINI_SERVER_SRC, "utf8");

  // --- servers.json (contract format: servers[], autoDiscover:false)
  const servers = manifests.map((manifestPath) => {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    return {
      id: manifest.serverId,
      displayName: manifest.serverId,
      transport: {
        type: "stdio",
        command: "node",
        args: [join(GEN, "mini-fake-server.mjs"), "--manifest", manifestPath],
      },
      trust: "trusted",
      enabled: true,
    };
  });
  const config = {
    autoDiscover: false,
    autoApproveAtOrAbove: "trusted",
    servers,
    skills: [],
    bundles: [],
  };
  writeFileSync(join(GEN, "servers.json"), JSON.stringify(config, null, 2), "utf8");
  return { manifests };
}

// --------------------------------------------------------------- isolation

function makeTempRoot() {
  const tmpBase = process.env["TMPDIR"] ?? "/tmp";
  const root = join(tmpBase, `ah-harness-e2e-${process.pid}-${Date.now()}`);
  const home = join(root, "home");
  const dirs = {
    HOME: home,
    USERPROFILE: home,
    APPDATA: join(root, "appdata", "roaming"),
    LOCALAPPDATA: join(root, "appdata", "local"),
    XDG_CACHE_HOME: join(home, ".cache"),
    XDG_CONFIG_HOME: join(home, ".config"),
    XDG_STATE_HOME: join(home, "state"),
    XDG_DATA_HOME: join(home, "data"),
    CODEX_HOME: join(root, "codex"),
    CLAUDE_CONFIG_DIR: join(root, "claude"),
    PI_CODING_AGENT_DIR: join(root, "pi-agent"),
    ACTION_HUB_CACHE: join(root, "ah", "catalog.json"),
    TMPDIR: join(root, "tmp"),
    TMP: join(root, "tmp"),
    TEMP: join(root, "tmp"),
    ACTION_HUB_CONFIG: join(root, "ah", "servers.json"),
    ACTION_HUB_SKILLS_DIR: join(root, "skills"),
    ACTION_HUB_DAEMON_DIR: join(root, "daemon"),
    ACTION_HUB_CREDENTIALS: join(root, "ah", "credentials.json"),
  };
  dirs["ACTION_HUB_CONTROL"] = join(root, "ah", "control.json");
  // The real owner home is determined independently of $HOME (checklist rule).
  // Refuse only paths inside the owner's app-state/harness dirs (not whole-home:
  // os.tmpdir() is under USERPROFILE on Windows). Separator-safe containment
  // via path.relative.
  const ownerHome = userInfo().homedir || homedir();
  // Full ISOLATION.md denylist. Checked unconditionally (pure path math), so a
  // var colliding even with a not-yet-existing owner dir is caught.
  const guardedDirs = [
    join(ownerHome, ".pi"),
    join(ownerHome, ".codex"),
    join(ownerHome, ".claude"),
    join(ownerHome, ".claude.json"),
    join(ownerHome, ".action-hub"),
    join(ownerHome, ".config", "action-hub"),
    join(ownerHome, ".cache", "action-hub"),
    join(ownerHome, ".config", "opencode"),
    join(ownerHome, ".local", "share", "opencode"),
    join(ownerHome, ".cursor"),
    join(ownerHome, ".copilot"),
    join(ownerHome, "Library", "Application Support", "Claude"),
    join(ownerHome, "Library", "Application Support", "Code"),
    join(ownerHome, "Library", "Application Support", "action-hub"),
    join(ownerHome, "Library", "Caches", "action-hub"),
    join(ownerHome, "Library", "Preferences", "action-hub"),
    join(ownerHome, "AppData", "Roaming", "action-hub"),
    join(ownerHome, "AppData", "Local", "action-hub"),
  ];
  // Real-home wildcard siblings: .claude*, .codex*, .cursor*, .copilot* and
  // friends are enumerated from the real home so a run root accidentally
  // derived from an inherited var pointing INSIDE such a dir is refused
  // before any write (S6-R3 #5). readdir failures are surfaced, not swallowed.
  let homeEntries;
  try {
    homeEntries = readdirSync(ownerHome);
  } catch (cause) {
    throw new Error(`isolation check aborted: cannot enumerate real home ${ownerHome}: ${cause?.message}`);
  }
  for (const entry of homeEntries) {
    if (/^\.(pi|codex|claude|cursor|copilot|action-hub|opencode)/.test(entry)) {
      guardedDirs.push(join(ownerHome, entry));
    }
  }
  const contains = (parent, child) => {
    const rel = relative(parent, resolve(child));
    return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
  };
  // Validate the proposed root FIRST — before any mkdir/write happens.
  if (guardedDirs.some((g) => contains(g, root))) {
    throw new Error(`isolation check failed: proposed run root ${root} lies inside real harness state`);
  }
  for (const [name, value] of Object.entries(dirs)) {
    for (const guarded of guardedDirs) {
      if (contains(guarded, String(value))) {
        throw new Error(`isolation check failed: ${name}=${value} resolves inside real harness state ${guarded}`);
      }
    }
  }
  const mkdirs = [
    root, home, dirs["TMPDIR"], dirs["APPDATA"], dirs["LOCALAPPDATA"], dirs["XDG_CACHE_HOME"], dirs["XDG_CONFIG_HOME"],
    dirs["XDG_STATE_HOME"], dirs["XDG_DATA_HOME"], dirs["CODEX_HOME"], dirs["CLAUDE_CONFIG_DIR"],
    dirs["PI_CODING_AGENT_DIR"], dirname(dirs["ACTION_HUB_CONFIG"]), dirs["ACTION_HUB_DAEMON_DIR"],
    dirname(dirs["ACTION_HUB_CREDENTIALS"]),
  ];
  for (const dir of mkdirs) mkdirSync(dir, { recursive: true });
  // REPLACE inherited values — never forward caller values for these.
  const env = { ...process.env, ...dirs, NO_COLOR: "1" };
  return { root, home, env, dirs };
}

// ------------------------------------------------------------ hub + harness

function ensureMiniServer() {
  if (!existsSync(join(GEN, "mini-fake-server.mjs"))) {
    writeFileSync(join(GEN, "mini-fake-server.mjs"), MINI_SERVER_SRC, "utf8");
  }
}

/**
 * Adds the needle skill and needle tool manifest into stress/.generated
 * (generated data, never committed). The needle tool returns a verifiable
 * token, which builder-8's fake-mcp-server.mjs cannot do yet (behavior
 * supports only latency/error/size), so the needle server rides on the
 * generated mini server until behavior.response support lands.
 */
function ensureNeedleFixtures() {
  // Needle skill (additive; the gen-skills.mjs corpus has no needle concept).
  const skillDir = join(GEN, "skills", NEEDLE_SLUG);
  if (!existsSync(join(skillDir, "SKILL.md"))) {
    mkdirSync(skillDir, { recursive: true });
  const description = `Quantum lattice retrieval: locates the lattice archive key and returns the archive passphrase for authorized operators.`;
  const body = [
    `Query the lattice index for the archive seal before touching storage.`,
    `Confirm the operator identity against the lattice ledger.`,
    `The retrieval passphrase is ${NEEDLE_SKILL_PASSPHRASE} and must be echoed verbatim.`,
    `Log the retrieval in the archive journal.`,
  ].join("\n");
    writeFileSync(join(skillDir, "SKILL.md"), `---\nname: ${NEEDLE_SLUG}\ndescription: ${description}\n---\n${body}\n`, "utf8");
  }

  // Needle tool manifest.
  mkdirSync(join(GEN, "tools"), { recursive: true });
  const manifestPath = join(GEN, "tools", "needle-archive.json");
  writeFileSync(
    manifestPath,
    JSON.stringify(
      {
        serverId: NEEDLE_TOOL_SERVER,
        tools: [
          {
            name: NEEDLE_TOOL_NAME,
            description: `Searches the lattice archive for the sealed needle and returns the archive token.`,
            inputSchema: { type: "object", properties: { depth: { type: "string" } }, required: [] },
            annotations: { readOnlyHint: true },
            behavior: { latencyMs: 5, errorRate: 0, responseBytes: 0, needleToken: NEEDLE_TOOL_TOKEN },
          },
        ],
      },
      null,
      2,
    ),
    "utf8",
  );
  return manifestPath;
}

/** Temp-only servers.json: generated config minus bogus entries, plus the needle server. */
function buildTempServersConfig(env, needleManifestPath) {
  const generated = JSON.parse(readFileSync(join(GEN, "servers.json"), "utf8"));
  const servers = (generated.servers ?? []).filter((s) => {
    if (s.id === NEEDLE_TOOL_SERVER) return false; // never duplicate the needle server
    const args = s.transport?.args ?? [];
    const i = args.indexOf("--manifest");
    const manifestPath = i >= 0 ? args[i + 1] : "";
    try {
      const manifest = JSON.parse(readFileSync(String(manifestPath), "utf8"));
      return typeof manifest.serverId === "string" && Array.isArray(manifest.tools);
    } catch {
      return false; // e.g. make-config's tools-queries.json artifact
    }
  });
  servers.unshift({
    id: NEEDLE_TOOL_SERVER,
    displayName: NEEDLE_TOOL_SERVER,
    transport: { type: "stdio", command: "node", args: [join(GEN, "mini-fake-server.mjs"), "--manifest", needleManifestPath] },
    trust: "trusted",
    enabled: true,
  });
  const tempConfig = join(env["HOME"], "servers.json");
  writeFileSync(tempConfig, JSON.stringify({ ...generated, servers, autoDiscover: false, autoApproveAtOrAbove: "trusted", skills: [] }, null, 2), "utf8");
  return tempConfig;
}

async function cliEntryPath(env) {
  const entry = join(REPO, "packages", "cli", "dist", "index.js");
  if (!existsSync(entry)) {
    const tsc = join(REPO, "node_modules", "typescript", "bin", "tsc");
    for (const pkg of ["core", "cli"]) {
      const r = await runAsync("node", [tsc, "-p", join(REPO, "packages", pkg, "tsconfig.json")], env, { timeout: 600000 });
      if (r.status !== 0) throw new Error(`build failed for ${pkg}: ${r.stderr}`);
    }
  }
  return entry;
}

async function installHarness(target, env, cli) {
  return runAsync("node", [cli, "harness", target, "install", "--write", "--json"], env);
}

/** Harness CLI target names (the runner key "claude" installs as "claude-code"). */
const HARNESS_TARGETS = { pi: "pi", codex: "codex", claude: "claude-code", opencode: "opencode" };

/** Rewires installed snippets from `<cli> start` to `<cli> connect` (daemon mode). */
function useDaemonSnippet(configPath, cli) {
  if (!existsSync(configPath)) return false;
  const doc = JSON.parse(readFileSync(configPath, "utf8"));
  const servers = doc["mcpServers"] ?? doc["mcp"] ?? doc["servers"];
  let changed = false;
  const rewireArray = (arr) => {
    for (let i = 0; i < arr.length; i++) {
      if (arr[i] === "start" && typeof arr[i - 1] === "string" && arr[i - 1].endsWith("index.js")) {
        arr[i] = "connect";
        changed = true;
      }
    }
  };
  for (const entry of Object.values(servers ?? {})) {
    if (Array.isArray(entry?.["command"])) {
      // opencode style: single command array [node, cli, start]
      rewireArray(entry["command"]);
    } else if (Array.isArray(entry?.["args"])) {
      rewireArray(entry["args"]);
    }
  }
  if (changed) writeFileSync(configPath, JSON.stringify(doc, null, 2), "utf8");
  return changed;
}

/** Warm the hub catalog cache in the temp HOME so harness cold starts are fast.
 *  createHubRuntime writes the cache on every boot; a short-lived `start` run
 *  is enough. Without this, hub cold start (~20 s at 15K actions) exceeds
 *  harness MCP init timeouts (codex default ~10 s, pi adapter 30 s). */
async function preWarmCache(env, cli) {
  // Poll the CONFIGURED cache file (ACTION_HUB_CACHE), not the XDG default.
  const cachePath = env["ACTION_HUB_CACHE"];
  const child = spawn("node", [cli, "start"], { env, stdio: ["ignore", "pipe", "pipe"], detached: true });
  let stdout = "";
  let stderr = "";
  child.stdout.on("data", (d) => (stdout += d)); // drain so the child never blocks
  child.stderr.on("data", (d) => (stderr += d));
  const killTreeWarm = (signal) => killTree(child.pid, signal);
  let wrote = false;
  for (let i = 0; i < 120; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (existsSync(cachePath)) { wrote = true; break; }
  }
  killTreeWarm("SIGTERM");
  if (child.pid !== undefined) await waitGone(child.pid, 3000);
  if (child.pid !== undefined && stillAlive(child.pid)) {
    killTreeWarm("SIGKILL");
    await waitGone(child.pid, 3000);
  }
  return wrote && existsSync(cachePath);
}

// ----------------------------------------------------------------- prompts

function skillPrompt() {
  return [
    `You have an "action_hub" MCP server available.`,
    `Call its search tool with query "${NEEDLE_SKILL_QUERY}" (limit 10).`,
    `In the results find the action with id "skill:${NEEDLE_SLUG}", then call the action_hub load tool with that id.`,
    `If and only if the load succeeds and the loaded content contains a retrieval passphrase, print exactly this line: ${SKILL_MARKER} <the passphrase>`,
    `Do nothing else.`,
  ].join(" ");
}

function toolPrompt() {
  return [
    `You have an "action_hub" MCP server available.`,
    `Call its search tool with query "${NEEDLE_TOOL_QUERY}" (limit 10).`,
    `Find the action with id "${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}" in the results, then call the action_hub execute/call tool to execute that action with arguments {}.`,
    `If and only if the executed response contains an ARCHIVE_TOKEN, print exactly this line: ${TOOL_MARKER} <the token value>`,
    `Do nothing else.`,
  ].join(" ");
}

// ------------------------------------------------------- harness runners

async function piSetup(env, root) {
  // Copy provider config the way builder-3 did for PR 44: from one rig seat's
  // agent dir (user login state; copied ONLY into the temp dir, never the repo).
  const seat = process.env["STRESS_PI_SEAT"]
    ? join(process.env["STRESS_PI_SEAT"], "agent")
    : join(homedir(), ".openrig", "state", "pi", "build-builder-10@action-hub", "agent");
  const agentDir = env["PI_CODING_AGENT_DIR"];
  for (const file of ["cliproxyapi.json", "cliproxyapi-models.json", "models-store.json", "auth.json"]) {
    const src = join(seat, file);
    if (existsSync(src)) cpSync(src, join(agentDir, file));
    else writeFileSync(join(agentDir, file), "{}\n", "utf8");
  }
  if (existsSync(join(seat, "settings.json"))) {
    cpSync(join(seat, "settings.json"), join(agentDir, "settings.json"));
  } else {
    writeFileSync(join(agentDir, "settings.json"), JSON.stringify({ packages: ["npm:@router-for-me/pi-cliproxyapi-provider@1.4.20"] }, null, 2), "utf8");
  }
  if (existsSync(join(seat, "npm"))) {
    cpSync(join(seat, "npm"), join(agentDir, "npm"), { recursive: true });
  }

  const adapterInNpm = existsSync(join(agentDir, "npm", "node_modules", "pi-mcp-adapter"));
  if (!adapterInNpm) {
    // Cache-aware npm install of the adapter (same as `pi install npm:pi-mcp-adapter`).
    const npmPkgPath = join(agentDir, "npm", "package.json");
    if (existsSync(npmPkgPath)) {
      const npmPkg = JSON.parse(readFileSync(npmPkgPath, "utf8"));
      npmPkg["dependencies"] ??= {};
      npmPkg["dependencies"]["pi-mcp-adapter"] = "^2.15.0";
      writeFileSync(npmPkgPath, JSON.stringify(npmPkg, null, 2), "utf8");
    }
    const install = await runAsync("npm", ["install", "--prefix", join(agentDir, "npm"), "--prefer-offline", "--no-audit", "--no-fund", "pi-mcp-adapter@^2.15.0"], env, { timeout: 180000 });
    if (!existsSync(join(agentDir, "npm", "node_modules", "pi-mcp-adapter"))) {
      return { ok: false, note: `pi-mcp-adapter unavailable (npm install failed: ${(install.stderr || install.stdout || "").slice(-200)})` };
    }
    // Register the adapter in settings.json packages (what `pi install` does).
    const settingsPath = join(agentDir, "settings.json");
    const settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    settings["packages"] ??= [];
    if (!settings["packages"].some((p) => String(p).includes("pi-mcp-adapter"))) {
      settings["packages"].push("npm:pi-mcp-adapter@2.15.0");
    }
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
  }
  return { ok: true };
}

async function runPi(env, prompt, timeout) {
  const models = JSON.parse(readFileSync(join(env["PI_CODING_AGENT_DIR"], "cliproxyapi-models.json"), "utf8"));
  const model = process.env["STRESS_PI_MODEL"] ?? models?.models?.[0]?.id ?? models?.[0]?.id ?? "claude-haiku-4-5-20251001";
  const r = await runAsync("pi", ["-p", "--no-session", "--provider", "cliproxyapi", "--model", model, prompt], env, { timeout });
  return { ...r, model };
}

async function runCodex(env, prompt, timeout) {
  // Credentials come from the user's login state (~/.codex/auth.json), copied
  // only into the temp HOME; the repo never receives secrets.
  const authSrc = join(homedir(), ".codex", "auth.json");
  // codex strips the parent env for MCP server spawns, so the stress config is
  // passed through the TOML env table; startup/tool timeouts are raised above
  // the hub's cold-start window (P1 finding: ~20 s at 15K actions).
  const entryCmd = env["ACTION_HUB_DAEMON_MODE"] ? "connect" : "start";
  const toml = [
    "[mcp_servers.action-hub]",
    `command = "node"`,
    `args = [ "${env["ACTION_HUB_CLI_ENTRY"]}", "${entryCmd}" ]`,
    "startup_timeout_ms = 180000",
    "tool_timeout_ms = 120000",
    "",
    "[mcp_servers.action-hub.env]",
    // Complete isolated set: codex strips the parent env for MCP spawns, so
    // every isolation var must be forwarded here explicitly (S6-R2 #1).
    `HOME = "${env["HOME"]}"`,
    `USERPROFILE = "${env["USERPROFILE"]}"`,
    `APPDATA = "${env["APPDATA"]}"`,
    `LOCALAPPDATA = "${env["LOCALAPPDATA"]}"`,
    `XDG_CACHE_HOME = "${env["XDG_CACHE_HOME"]}"`,
    `XDG_CONFIG_HOME = "${env["XDG_CONFIG_HOME"]}"`,
    `XDG_STATE_HOME = "${env["XDG_STATE_HOME"]}"`,
    `XDG_DATA_HOME = "${env["XDG_DATA_HOME"]}"`,
    `TMPDIR = "${env["TMPDIR"]}"`,
    `TMP = "${env["TMP"]}"`,
    `TEMP = "${env["TEMP"]}"`,
    `ACTION_HUB_CONFIG = "${env["ACTION_HUB_CONFIG"]}"`,
    `ACTION_HUB_CACHE = "${env["ACTION_HUB_CACHE"]}"`,
    `ACTION_HUB_SKILLS_DIR = "${env["ACTION_HUB_SKILLS_DIR"]}"`,
    `ACTION_HUB_CREDENTIALS = "${env["ACTION_HUB_CREDENTIALS"]}"`,
    `ACTION_HUB_CONTROL = "${env["ACTION_HUB_CONTROL"]}"`,
    `PI_CODING_AGENT_DIR = "${env["PI_CODING_AGENT_DIR"]}"`,
    `CODEX_HOME = "${env["CODEX_HOME"]}"`,
    `CLAUDE_CONFIG_DIR = "${env["CLAUDE_CONFIG_DIR"]}"`,
    `NO_COLOR = "1"`,
    `ACTION_HUB_DAEMON_DIR = "${env["ACTION_HUB_DAEMON_DIR"]}"`,
    "",
  ].join("\n");
  // codex 0.154 reads $CODEX_HOME when set and $HOME/.codex otherwise; write
  // both so the config lands regardless of which one this build honors.
  const codexDirs = [...new Set([env["CODEX_HOME"], join(env["HOME"], ".codex")].filter(Boolean))];
  for (const codexDir of codexDirs) {
    mkdirSync(codexDir, { recursive: true });
    if (existsSync(authSrc)) cpSync(authSrc, join(codexDir, "auth.json"));
    writeFileSync(join(codexDir, "config.toml"), toml, "utf8");
  }
  const r = await runAsync("codex", ["exec", "--dangerously-bypass-approvals-and-sandbox", "--skip-git-repo-check", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

async function runClaude(env, prompt, timeout) {
  const r = await runAsync("claude", ["-p", "--dangerously-skip-permissions", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

async function runOpencode(env, prompt, timeout) {
  // opencode credentials: copy the user's auth state (login state only).
  const authSrc = join(homedir(), ".local", "share", "opencode", "auth.json");
  const authDst = join(env["XDG_DATA_HOME"], "opencode", "auth.json");
  if (existsSync(authSrc)) {
    mkdirSync(dirname(authDst), { recursive: true });
    cpSync(authSrc, authDst);
  }
  const r = await runAsync("opencode", ["run", prompt], env, { timeout, cwd: env["HOME"] });
  return r;
}

const RUNNERS = {
  pi: { run: runPi, prompt: skillPrompt, needleKind: "skill", configPath: (env) => join(env["PI_CODING_AGENT_DIR"], "mcp.json") },
  codex: { run: runCodex, prompt: toolPrompt, needleKind: "tool", configPath: (env) => join(env["HOME"], ".codex", "config.toml") },
  claude: { run: runClaude, prompt: skillPrompt, needleKind: "skill", configPath: (env) => join(env["HOME"], ".claude.json") },
  opencode: { run: runOpencode, prompt: toolPrompt, needleKind: "tool", configPath: (env) => join(env["XDG_CONFIG_HOME"] ?? join(env["HOME"], ".config"), "opencode", "opencode.json") },
};

// ---------------------------------------------------------------- metrics

async function measureSearchSize(env, query, cli) {
  const t0 = Date.now();
  const r = await runAsync("node", [cli, "test-search", query, "--json", "--limit", "10"], env, { timeout: 120000 });
  return { bytes: r.stdout.length, wallMs: Date.now() - t0, ok: r.status === 0, error: r.status !== 0 ? r.stderr.slice(-300) : undefined };
}

function evaluateHarness(name, result, needle) {
  const out = `${result.stdout}\n${result.stderr}`;
  const foundId = out.includes(needle.id);
  const marker = needle.kind === "skill" ? SKILL_MARKER : TOOL_MARKER;
  // Some harnesses (codex exec) print the final answer on stderr, so marker
  // detection runs over combined output; the latest matching line wins.
  const markerLines = out.split("\n").filter((l) => l.includes(marker));
  const markerLine = markerLines[markerLines.length - 1];
  let tokenOk = false;
  if (markerLine) {
    tokenOk = needle.kind === "tool" ? markerLine.includes(needle.token) : markerLine.includes(needle.passphrase);
  }
  return {
    harness: name,
    exitCode: result.status,
    timedOut: Boolean(result.timedOut),
    foundNeedleId: foundId,
    markerPrinted: Boolean(markerLine),
    // Success = clean exit AND the harness proved it reached the needle:
    // marker printed with the verifiable secret (passphrase for skills, token
    // for tools). A killed/timeout/nonzero run is a failure even if it happened
    // to print the marker first.
    success: result.status === 0 && !result.timedOut && Boolean(markerLine) && tokenOk,
    turns: null, // turn counts are harness-specific; parsed opportunistically below
    wallMs: result.wallMs,
    outputChars: result.stdout.length,
    outputTail: out.slice(-400),
    error: result.status !== 0 ? (result.stderr || result.stdout || "").slice(-400) : undefined,
  };
}

/** Direct JSON-RPC handshake + needle tool execution against the generated
 *  mini server (clean-generation proof). Resolves { ok, error?, token? }. */
function needleServerHandshake(env, needleManifestPath) {
  return new Promise((done) => {
    const child = spawn("node", [join(GEN, "mini-fake-server.mjs"), "--manifest", needleManifestPath], {
      env, stdio: ["pipe", "pipe", "pipe"],
    });
    let out = "";
    let err = "";
    let settled = false;
    const finish = (result) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try { child.kill("SIGKILL"); } catch { /* gone */ }
      done(result);
    };
    const timer = setTimeout(() => finish({ ok: false, error: "handshake timeout; out=" + out.slice(-200) + " err=" + err.slice(-200) }), 15000);
    child.stdout.on("data", (d) => {
      out += d;
      for (const line of out.split("\n")) {
        if (!line.trim()) continue;
        let msg; try { msg = JSON.parse(line); } catch { continue; }
        if (msg.id === 1) {
          child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }) + "\n");
          child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id: 2, method: "tools/call", params: { name: NEEDLE_TOOL_NAME, arguments: { query: "lattice" } } }) + "\n");
        } else if (msg.id === 2) {
          const text = msg.result?.content?.[0]?.text ?? "";
          const ok = !msg.result?.isError && text.includes(NEEDLE_TOOL_TOKEN);
          finish(ok ? { ok: true, token: NEEDLE_TOOL_TOKEN } : { ok: false, error: "needle token missing in result: " + text.slice(-200) });
        }
      }
    });
    child.stderr.on("data", (d) => (err += d));
    child.on("error", (cause) => finish({ ok: false, error: "spawn error: " + cause?.message }));
    child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "harness-e2e", version: "1.0.0" } } }) + "\n");
  });
}

/** Cross-platform process-tree kill: POSIX group kill, Windows taskkill /T. */
function killTree(pid, signal = "SIGTERM") {
  if (pid === undefined || pid === null || pid <= 0) return;
  if (process.platform === "win32") {
    spawn("taskkill", ["/T", "/F", "/PID", String(pid)], { stdio: "ignore" });
    return;
  }
  try { process.kill(-pid, signal); } catch { /* already gone */ }
  try { process.kill(pid, signal); } catch { /* already gone */ }
}

/** Poll until the pid is gone (bounded) instead of fixed sleeps. */
async function waitGone(pid, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (!stillAlive(pid)) return true;
    await new Promise((r) => setTimeout(r, 100));
  }
  return !stillAlive(pid);
}

function stillAlive(pid) {
  try { process.kill(pid, 0); return true; } catch { return false; }
}

// ------------------------------------------------------------------- main

async function main() {
  const started = Date.now();
  const summary = {
    script: "harness-e2e",
    mode: MODE,
    ok: false,
    fixtures: {},
    harnesses: [],
    concurrency: null,
    searchOutputBytes: null,
    errors: [],
  };
  let daemonChild = null;
  let lastEnv = null;
  let daemonPid = null;

  try {
    const { root, home, env, dirs } = makeTempRoot();
    lastEnv = env;
    mkdirSync(RESULTS, { recursive: true });
    mkdirSync(join(root, "skills"), { recursive: true });

    // Fixture generation FIRST (clean clones have no stress/.generated): run
    // the builders' generators when present, else the self-sufficient fallback.
    const buildersScripts =
      existsSync(join(STRESS, "gen-skills.mjs")) &&
      existsSync(join(STRESS, "gen-tools.mjs")) &&
      existsSync(join(STRESS, "make-config.mjs"));
    if (!existsSync(join(GEN, "servers.json"))) {
      if (buildersScripts) {
        // Builders' generators exist: run them for the real corpus (44 servers,
        // 10,000 tools, 5,000 skills) instead of falling back to fixtures.
        for (const script of ["gen-skills.mjs", "gen-tools.mjs", "make-config.mjs"]) {
          const r = await runAsync("node", [join(STRESS, script)], env, { timeout: 600000, cwd: REPO });
          if (r.status !== 0) throw new Error(`${script} failed: ${(r.stderr || "").slice(-300)}`);
        }
        summary.fixtures = { source: "builders-scripts-run", generatedAt: new Date().toISOString() };
      } else {
        summary.fixtures = {
          source: "harness-e2e-fallback",
          generatedAt: new Date().toISOString(),
          fillerSkills: FILLER_SKILLS,
          fillerToolsPerServer: FILLER_TOOLS_PER_SERVER,
        };
        generateFixtures();
      }
    } else {
      summary.fixtures = { source: buildersScripts ? "builders-output" : "preexisting-generated" };
    }

    ensureMiniServer();
    const needleManifestPath = ensureNeedleFixtures();
    // Clean-generation handshake: launch the freshly generated mini server
    // directly and execute the needle tool — proves the generated source
    // actually runs and returns the token (S6-R3 #2).
    summary.fixtures.needleHandshake = await needleServerHandshake(env, needleManifestPath);
    if (!summary.fixtures.needleHandshake.ok) {
      summary.errors.push(`needle server handshake failed: ${summary.fixtures.needleHandshake.error}`);
    }
    const generatedServerCount = JSON.parse(readFileSync(join(GEN, "servers.json"), "utf8")).servers?.length ?? 0;

    // Needle fixtures + temp-only config (the generated servers.json is never
    // modified in place; bogus entries like make-config's tools-queries.json
    // artifact are filtered in the temp copy).
    // Builders' scripts and the TypeScript build must never run with real
    // process.env: the isolated env exists before anything is spawned.
    const cli = await cliEntryPath(env);
    // Skills must live INSIDE the run root (S6-R2): copy the generated corpus.
    const tempSkillsDir = join(root, "skills");
    cpSync(join(GEN, "skills"), tempSkillsDir, { recursive: true });
    env["ACTION_HUB_SKILLS_DIR"] = tempSkillsDir;
    env["ACTION_HUB_CONFIG"] = buildTempServersConfig(env, needleManifestPath);
    env["ACTION_HUB_CLI_ENTRY"] = cli;
    // FINAL containment revalidation: every path-valued var in the FINAL env
    // (after reassignment) must lie under the temp root, separator-safe.
    const contained = (parent, child) => {
      const rel = relative(parent, resolve(child));
      return rel !== "" && !rel.startsWith("..") && !isAbsolute(rel);
    };
    const PATH_VARS = [
      "HOME", "USERPROFILE", "APPDATA", "LOCALAPPDATA", "TMPDIR",
      "XDG_CACHE_HOME", "XDG_CONFIG_HOME", "XDG_STATE_HOME", "XDG_DATA_HOME",
      "PI_CODING_AGENT_DIR", "CODEX_HOME", "CLAUDE_CONFIG_DIR",
      "ACTION_HUB_CONFIG", "ACTION_HUB_CACHE", "ACTION_HUB_SKILLS_DIR",
      "ACTION_HUB_DAEMON_DIR", "ACTION_HUB_CREDENTIALS", "ACTION_HUB_CONTROL",
    ];
    for (const k of PATH_VARS) {
      const v = env[k];
      if (typeof v === "string" && v && !contained(root, v)) {
        summary.errors.push(`containment: ${k}=${v} is not under ${root}`);
      }
    }
    if (summary.errors.some((e) => e.startsWith("containment:"))) throw new Error("isolation containment revalidation failed");
    if (MODE === "daemon") {
      env["ACTION_HUB_DAEMON_MODE"] = "1";
      if (FAULT === "daemon-start") {
        writeFileSync(join(root, "daemon-blocker"), "x", "utf8");
        env["ACTION_HUB_DAEMON_DIR"] = join(root, "daemon-blocker", "daemon"); // parent is a file
        summary.fault = "daemon-start";
      }
    }
    summary.tempRoot = root; // removed in finally when !KEEP

    // Fleet validation: report actual indexed counts and gate full-scale runs.
    const tempConfig = JSON.parse(readFileSync(env["ACTION_HUB_CONFIG"], "utf8"));
    let toolCount = 0;
    for (const srv of tempConfig.servers) {
      const args = srv.transport?.args ?? [];
      const i = args.indexOf("--manifest");
      if (i >= 0) {
        try { toolCount += (JSON.parse(readFileSync(String(args[i + 1]), "utf8")).tools ?? []).length; } catch { /* needle registered by path below */ }
      }
    }
    const skillCount = readdirSync(env["ACTION_HUB_SKILLS_DIR"]).filter((d) => existsSync(join(env["ACTION_HUB_SKILLS_DIR"], d, "SKILL.md"))).length;
    summary.fleet = {
      servers: tempConfig.servers.length,
      tools: toolCount,
      skills: skillCount,
      fullScale: tempConfig.servers.length >= 45 && toolCount >= 10001 && skillCount >= 5001,
    };
    if (String(summary.fixtures.source).startsWith("builders") && !summary.fleet.fullScale) {
      summary.errors.push(`fleet validation failed: expected 45 servers / 10,001 tools / 5,001 skills, got ${tempConfig.servers.length}/${toolCount}/${skillCount}`);
    }
    summary.fixtures.tempConfigServers = tempConfig.servers.length;

    // Hub load check (COLD — before any cache warm-up): search to verify the
    // fixtures actually serve and to measure the cold-indexed search.
    const coldProbe = await measureSearchSize(env, NEEDLE_SKILL_QUERY, cli);
    summary.fixtures.probeOk = coldProbe.ok;
    summary.searchOutputBytes = coldProbe.bytes;
    if (!coldProbe.ok) summary.errors.push(`probe failed: ${coldProbe.error}`);

    // Warm the CONFIGURED cache (ACTION_HUB_CACHE) once; then measure warm.
    summary.cacheWarm = await preWarmCache(env, cli);
    const warmProbe = summary.cacheWarm ? await measureSearchSize(env, NEEDLE_SKILL_QUERY, cli) : null;
    summary.coldWarm = {
      coldSearchMs: coldProbe.wallMs ?? null,
      warmSearchMs: warmProbe?.wallMs ?? null,
      cacheWarm: summary.cacheWarm,
    };

    // Optional shared daemon (mode=daemon): up to 3 harnesses against one daemon.
    if (MODE === "daemon") {
      // daemon start's built-in readiness wait is 15 s (START_TIMEOUT_MS in
      // daemon.ts) but cold indexing at 15K actions can take ~20 s+, so poll
      // for the state file well past the CLI's own give-up.
      daemonChild = spawn("node", [cli, "daemon", "start"], { env, stdio: ["ignore", "pipe", "pipe"], detached: true });
      daemonChild.stdout.on("data", () => {}); // drain
      daemonChild.stderr.on("data", () => {}); // drain
      // F35: with --fault, HARNESS_E2E_READINESS_MS may shorten the readiness
      // wait so the fault proof runs in seconds; honoured ONLY under --fault —
      // the production budget (150 s) is unchanged.
      const readinessMs = FAULT !== "none" && process.env["HARNESS_E2E_READINESS_MS"]
        ? Math.max(1000, Number(process.env["HARNESS_E2E_READINESS_MS"]) || 150000)
        : 150000;
      for (let i = 0; i < Math.ceil(readinessMs / 500); i++) {
        await new Promise((r) => setTimeout(r, 500));
        if (existsSync(join(env["ACTION_HUB_DAEMON_DIR"], "daemon.json"))) break;
      }
      summary.daemonStarted = existsSync(join(env["ACTION_HUB_DAEMON_DIR"], "daemon.json"));
      if (!summary.daemonStarted) {
        // HARD GATE (S6-R4): daemon mode must actually share a daemon; never
        // silently fall back to per-harness standalone hubs.
        throw new Error("daemon mode: daemon did not reach readiness (no daemon.json) within 150s");
      }
      if (summary.daemonStarted) {
        try {
          const state = JSON.parse(readFileSync(join(env["ACTION_HUB_DAEMON_DIR"], "daemon.json"), "utf8"));
          daemonPid = Number(state.pid ?? state.daemonPid ?? 0) || null;
          summary.daemonPid = daemonPid;
        } catch (cause) {
          summary.errors.push(`daemon state unreadable: ${cause?.message}`);
          summary.daemonStarted = false;
        }
      }
      if (!daemonPid || daemonPid <= 0 || !stillAlive(daemonPid)) {
        throw new Error(`daemon mode: no valid live daemon pid recorded (got ${daemonPid})`);
      }
    }

    // Install per harness
    const installs = {};
    for (const h of HARNESS_LIST) {
      const def = RUNNERS[h];
      if (!def) continue;
      const inst = await installHarness(HARNESS_TARGETS[h] ?? h, env, cli);
      installs[h] = inst.status === 0;
      if (!installs[h]) summary.errors.push(`${h} install failed: ${(inst.stderr || "").slice(-300)}`);
    }
    // Rewiring gate: in daemon mode every harness must be rewired to connect
    // before the concurrent run; a failure aborts instead of silently
    // exercising standalone hubs (S6-R4).
    if (MODE === "daemon") {
      const rewireFailures = [];
      for (const h of HARNESS_LIST) {
        if (!installs[h]) continue;
        const def = RUNNERS[h];
        if (def.configPath(env).endsWith(".json")) {
          if (!useDaemonSnippet(def.configPath(env), cli)) rewireFailures.push(h);
        } else if (h === "codex") {
          summary.codexDaemonToml = true; // runCodex writes connect-mode TOML directly
        } else {
          rewireFailures.push(h);
        }
      }
      if (rewireFailures.length) throw new Error(`daemon mode: connect rewiring failed for: ${rewireFailures.join(", ")}`);
    }
    summary.installs = installs;

    if (HARNESS_LIST.includes("pi") && installs["pi"]) {
      const piSetupResult = await piSetup(env, root);
      if (!piSetupResult.ok) {
        summary.errors.push(`pi setup: ${piSetupResult.note}`);
        installs["pi"] = false;
        summary.installs = installs;
      }
    }

    const needles = {
      skill: { id: `skill:${NEEDLE_SLUG}`, kind: "skill", passphrase: NEEDLE_SKILL_PASSPHRASE },
      tool: { id: `${NEEDLE_TOOL_SERVER}:${NEEDLE_TOOL_NAME}`, kind: "tool", token: NEEDLE_TOOL_TOKEN },
    };

    const runOne = async (h) => {
      const def = RUNNERS[h];
      const t0 = Date.now();
      const result = await def.run(env, def.prompt(), TIMEOUT_MS);
      result.wallMs = Date.now() - t0;
      return evaluateHarness(h, result, needles[def.needleKind]);
    };

    // Sequential runs
    const results = [];
    for (const h of HARNESS_LIST) {
      if (!installs[h]) continue;
      try {
        results.push(await runOne(h));
      } catch (cause) {
        summary.errors.push(`${h} run threw: ${cause?.message ?? String(cause)}`);
      }
    }
    summary.harnesses = results;

    // Concurrency: 3 harnesses at once against the shared daemon
    if (MODE === "daemon") {
      const concurrent = HARNESS_LIST.filter((h) => installs[h]).slice(0, 3);
      if (concurrent.length < 1) throw new Error("daemon mode: no installed harness to run concurrently");
      const t0 = Date.now();
      const outcomes = await Promise.all(concurrent.map((h) => runOne(h).catch((cause) => ({ harness: h, success: false, error: String(cause) }))));
      summary.concurrency = { harnesses: concurrent, expected: concurrent.length, wallMs: Date.now() - t0, results: outcomes };
      if (outcomes.length !== concurrent.length) {
        throw new Error(`daemon mode: concurrency produced ${outcomes.length}/${concurrent.length} results`);
      }
    }

    if (daemonChild) {
      await runAsync("node", [cli, "daemon", "stop"], env, { timeout: 60000 });
      try { daemonChild.kill("SIGKILL"); } catch { /* already gone */ }
    }

    summary.wallMs = Date.now() - started;
  } catch (cause) {
    summary.errors.push(`fatal: ${cause?.stack ?? String(cause)}`);
  } finally {
    summary.wallMs = Date.now() - started; // always present, even on failure
    // Orphan safety (S6-R3 #6/#7): stop the daemon by CLI (result checked),
    // then by the recorded pid group, then verify it is gone. Root removal
    // happens only AFTER teardown so daemon.json stays readable on failure.
    let rootPath = null;
    if (daemonChild) killTree(daemonChild.pid, "SIGTERM");
    if (lastEnv) {
      const stateFile = join(lastEnv["ACTION_HUB_DAEMON_DIR"], "daemon.json");
      // 1. ask the CLI to stop it and CHECK the result
      if (MODE === "daemon") {
        try {
          const stop = await runAsync("node", [lastEnv["ACTION_HUB_CLI_ENTRY"], "daemon", "stop"], lastEnv, { timeout: 20000 });
          if (stop.status !== 0 && existsSync(stateFile)) {
            summary.errors.push(`daemon stop exited ${stop.status} and daemon.json remains`);
          }
        } catch (cause) {
          summary.errors.push(`daemon stop failed: ${cause?.message}`);
        }
      }
      // 2. recorded-pid fallback (group TERM -> wait -> KILL -> wait)
      let pid = daemonPid;
      if (!pid && existsSync(stateFile)) {
        try { pid = Number(JSON.parse(readFileSync(stateFile, "utf8")).pid ?? 0) || null; } catch { /* ignore */ }
      }
      if (pid) {
        killTree(pid, "SIGTERM");
        if (!(await waitGone(pid, 3000))) {
          killTree(pid, "SIGKILL");
          if (!(await waitGone(pid, 3000))) {
            summary.errors.push(`orphan: daemon pid ${pid} survived SIGKILL`);
          }
        }
      }
      // 3. state file must be gone; remove only after survivors confirmed dead
      if (existsSync(stateFile) && !summary.errors.some((e) => e.startsWith("orphan:"))) {
        try { rmSync(stateFile); } catch { /* ignore */ }
      }
      rootPath = lastEnv["TMPDIR"] ? dirname(lastEnv["TMPDIR"]) : null; // TMPDIR = root/tmp
      if (rootPath && !KEEP) {
        try { rmSync(rootPath, { recursive: true, force: true }); } catch { /* best effort */ }
      }
    }
  }

  const concurrencyOk = summary.concurrency
    ? MODE === "daemon"
      ? // Daemon gate (S6-R4): a shared daemon must have been exercised.
        summary.daemonStarted === true &&
        Number(summary.daemonPid ?? 0) > 0 &&
        summary.concurrency.results.length === summary.concurrency.expected &&
        summary.concurrency.results.every((h) => h.success)
      : summary.concurrency.results.every((h) => h.success)
    : true;
  summary.ok = summary.errors.length === 0 &&
    (summary.harnesses?.length ?? 0) > 0 &&
    summary.harnesses.every((h) => h.success) &&
    concurrencyOk;
  writeFileSync(join(RESULTS, "harness-e2e.json"), JSON.stringify(summary, null, 2), "utf8");
  console.log(JSON.stringify(summary));
  if (!summary.ok) process.exitCode = 1;
}

function daemonRunningCheck(summary) {
  return MODE === "daemon" && summary.daemonStarted === true;
}

await main();