#!/usr/bin/env node
/**
 * Build stress test configuration from generated tool manifests.
 *
 * Reads every stress/.generated/tools/*.json (fake MCP server manifests) and
 * writes:
 *   stress/.generated/servers.json  - hub config with stdio server entries
 *   stress/.generated/env.sh        - isolation environment variables
 *
 * Options:
 *   --http-count N   additionally expose the first N manifests as HTTP
 *                    servers (fake server started on sequential ports)
 *   --out DIR        output directory (default stress/.generated)
 *   --root DIR       repo root for relative paths (default: cwd)
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));

function arg(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : fallback;
}

const httpCount = parseInt(arg("--http-count", "0"), 10);
const outDir = resolve(arg("--out", join(scriptDir, ".generated")));
const root = resolve(arg("--root", process.cwd()));
const basePort = parseInt(arg("--base-port", "41000"), 10);

const toolsDir = join(scriptDir, ".generated", "tools");
const files = readdirSync(toolsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

if (files.length === 0) {
  console.error(`no manifests found in ${toolsDir}`);
  process.exit(1);
}

const serverPath = relative(root, join(scriptDir, "fake-mcp-server.mjs"));
const servers = [];
const envExports = [];
const httpProcesses = [];

for (const [i, file] of files.entries()) {
  const manifestPath = relative(root, join(toolsDir, file));
  const manifest = JSON.parse(readFileSync(join(toolsDir, file), "utf8"));
  const serverArgs = [serverPath, "--manifest", manifestPath];
  const name = manifest.serverId ?? manifest.name ?? file.replace(/\.json$/, "");

  // Always emit a stdio entry.
  servers.push({
    id: name,
    displayName: `Fake ${name} (stdio)`,
    transport: { type: "stdio", command: "node", args: serverArgs },
  });

  // Optionally also expose this manifest over HTTP.
  if (i < httpCount) {
    const port = basePort + i;
    servers.push({
      id: `${name}-http`,
      displayName: `Fake ${name} (http)`,
      transport: { type: "http", url: `http://127.0.0.1:${port}/mcp` },
    });
    httpProcesses.push(
      `node ${JSON.stringify(serverPath)} --manifest ${JSON.stringify(manifestPath)} --transport http --port ${port} &`,
    );
  }

  envExports.push(`# ${manifestPath}`);
  if (manifest.env) {
    for (const [k, v] of Object.entries(manifest.env)) {
      envExports.push(`export ${k}=${JSON.stringify(v)}`);
    }
  }
}

mkdirSync(outDir, { recursive: true });
const config = { servers, autoDiscover: false };
writeFileSync(
  join(outDir, "servers.json"),
  JSON.stringify(config, null, 2) + "\n",
);
writeFileSync(
  join(outDir, "env.sh"),
  [
    "#!/bin/sh",
    "# Isolation environment for the Action Hub stress run.",
    "# Generated by stress/make-config.mjs - do not edit by hand.",
    ...envExports,
    ...(httpProcesses.length
      ? [
          "",
          "# Start HTTP fake servers (background).",
          ...httpProcesses,
        ]
      : []),
    "",
  ].join("\n"),
);
console.log(
  `wrote ${join(outDir, "servers.json")} (${servers.length} servers: ${files.length} stdio${
    httpCount ? `, ${httpCount} http` : ""
  }) and ${join(outDir, "env.sh")}`,
);
