#!/usr/bin/env node
/**
 * Build stress test configuration from generated tool manifests.
 *
 * Reads every stress/.generated/tools/*.json (fake MCP server manifests) and
 * writes:
 *   stress/.generated/servers.json  - hub config with stdio server entries
 *   stress/.generated/env.sh        - isolation environment variables
 *
 * Options:
 *   --http-count N   additionally expose the first N manifests as HTTP
 *                    servers (fake server started on sequential ports)
 *   --out DIR        output directory (default stress/.generated)
 *   --root DIR       repo root for relative paths (default: cwd)
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));

function arg(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : fallback;
}

const httpCount = parseInt(arg("--http-count", "0"), 10);
const outDir = resolve(arg("--out", join(scriptDir, ".generated")));
const root = resolve(arg("--root", process.cwd()));
const basePort = parseInt(arg("--base-port", "41000"), 10);

const toolsDir = join(scriptDir, ".generated", "tools");
const files = readdirSync(toolsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

if (files.length === 0) {
  console.error(`no manifests found in ${toolsDir}`);
  process.exit(1);
}

// Absolute paths: runners may cwd anywhere (builder-10 sanity note).
const serverPath = join(scriptDir, "fake-mcp-server.mjs");
const servers = [];
const envExports = [];
const httpProcesses = [];

for (const [i, file] of files.entries()) {
  const manifestPath = join(toolsDir, file); // absolute: survives any launcher cwd
  const manifest = JSON.parse(readFileSync(join(toolsDir, file), "utf8"));
  const serverArgs = [serverPath, "--manifest", manifestPath];
  const name = manifest.serverId ?? manifest.name ?? file.replace(/\.json$/, "");

  // Always emit a stdio entry.
  servers.push({
    id: name,
    displayName: `Fake ${name} (stdio)`,
    transport: { type: "stdio", command: "node", args: serverArgs },
  });

  // Optionally also expose this manifest over HTTP.
  if (i < httpCount) {
    const port = basePort + i;
    servers.push({
      id: `${name}-http`,
      displayName: `Fake ${name} (http)`,
      transport: { type: "http", url: `http://127.0.0.1:${port}/mcp` },
    });
    httpProcesses.push(
      `node ${JSON.stringify(serverPath)} --manifest ${JSON.stringify(manifestPath)} --transport http --port ${port} &`,
    );
  }

  envExports.push(`# ${manifestPath}`);
  if (manifest.env) {
    for (const [k, v] of Object.entries(manifest.env)) {
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(k)) {
        console.error(`invalid env key skipped: ${JSON.stringify(k)}`);
        process.exitCode = 1;
        continue;
      }
      envExports.push(`export ${k}=${shQuote(String(v))}`);
    }
  }
}

// POSIX-safe single-quote escaping: ' -> '\'' — values are emitted
// literally, so shell metacharacters ($, backticks) in manifest env values
// can never execute when env.sh is sourced.
function shQuote(value) {
  return "'" + String(value).replaceAll("'", "'\\''") + "'";
}

// Contract isolation vars (CONTRACT.md): sourced env.sh must point every
// variable at generated sandbox paths, never at the operator's real home.
function isolationExports() {
  const sandbox = join(outDir, "sandbox");
  return [
    `export HOME=${shQuote(join(sandbox, "home"))}`,
    `export XDG_CACHE_HOME=${shQuote(join(sandbox, "cache"))}`,
    `export XDG_CONFIG_HOME=${shQuote(join(sandbox, "config"))}`,
    `export ACTION_HUB_CONFIG=${shQuote(join(outDir, "servers.json"))}`,
    `export ACTION_HUB_SKILLS_DIR=${shQuote(join(sandbox, "skills"))}`,
    `export PI_CODING_AGENT_DIR=${shQuote(join(sandbox, "pi"))}`,
  ];
}

mkdirSync(join(outDir, "sandbox", "home"), { recursive: true });
mkdirSync(join(outDir, "sandbox", "cache"), { recursive: true });
mkdirSync(join(outDir, "sandbox", "config"), { recursive: true });
mkdirSync(join(outDir, "sandbox", "skills"), { recursive: true });
mkdirSync(join(outDir, "sandbox", "pi"), { recursive: true });
const config = { servers, autoDiscover: false };
const serversPath = join(outDir, "servers.json");
writeFileSync(serversPath, JSON.stringify(config, null, 2) + "\n");

// env.sh is export-only (CONTRACT.md hard rule 2): it must never launch
// servers or otherwise mutate state — sourcing it must only point the six
// contract isolation variables at generated sandbox paths.
const envSh = join(outDir, "env.sh");
writeFileSync(
  envSh,
  [
    "#!/bin/sh",
    "# Isolation environment for the Action Hub stress run.",
    "# Generated by stress/make-config.mjs - do not edit by hand.",
    "# Export-only by design: launches are the orchestrator's job.",
    "# Source me: . stress/.generated/env.sh",
    ...isolationExports(),
    "",
    "# Manifest-declared env vars (single-quoted, keys validated):",
    ...envExports,
    "",
  ].join("\n"),
);

// Evidence artifact + JSON summary (CONTRACT.md output rule).
const summary = {
  script: "make-config",
  serverCount: servers.length,
  manifestCount: files.length,
  httpCount,
  autoDiscover: false,
  paths: {
    serversJson: serversPath,
    envSh: envSh,
    sandboxHome: join(outDir, "sandbox", "home"),
  },
  nodeVersion: process.version,
  generatedAt: new Date().toISOString(),
};
const resultsFile = join(outDir, "results", "make-config.json");
mkdirSync(join(outDir, "results"), { recursive: true });
writeFileSync(resultsFile, JSON.stringify(summary, null, 2) + "\n");
console.log(JSON.stringify(summary));
