// Generates Windows Package Manager (winget) v1.6 manifests for the Action Hub
// portable CLI binary. Reads SHA256SUMS.txt for the windows-x64 installer hash.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import {
  repoRoot,
  repoSlug,
  releaseBaseUrl,
  parseChecksums,
  readCliVersion,
} from "./lib/util.mjs";

const PACKAGE_ID = "SolomonWakhungu.ActionHub";
const MANIFEST_VERSION = "1.6.0";

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--version" && argv[i + 1]) args.version = argv[++i];
    else if (argv[i] === "--checksums" && argv[i + 1]) args.checksums = resolve(argv[++i]);
    else if (argv[i] === "--out" && argv[i + 1]) args.out = resolve(argv[++i]);
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const version = args.version ?? (await readCliVersion());
  const checksumsPath = args.checksums ?? resolve(repoRoot, "dist-bin", "SHA256SUMS.txt");
  const repo = repoSlug();
  const base = releaseBaseUrl(version, repo);
  const outDir = args.out ?? resolve(repoRoot, "packaging", "winget", PACKAGE_ID, version);

  const map = parseChecksums(await readFile(checksumsPath, "utf8"));
  const sha = map["action-hub-windows-x64.exe"];
  if (!sha) throw new Error('SHA256SUMS is missing an entry for "action-hub-windows-x64.exe"');
  const shaUpper = sha.toUpperCase();

  const versionManifest = `# Generated by scripts/gen-winget.mjs. Do not edit by hand.
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ${MANIFEST_VERSION}
`;

  const localeManifest = `# Generated by scripts/gen-winget.mjs. Do not edit by hand.
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: Solomon Wakhungu
PublisherUrl: https://github.com/1solomonwakhungu
PublisherSupportUrl: https://github.com/${repo}/issues
Author: Solomon Wakhungu
PackageName: Action Hub
PackageUrl: https://github.com/${repo}
License: MIT
LicenseUrl: https://github.com/${repo}/blob/main/LICENSE
ShortDescription: Indexed, on-demand capability layer for MCP servers and skills.
Description: >-
  Action Hub replaces an eager MCP tool surface with an indexed, on-demand
  capability layer, exposing a single search/load/execute tool over stdio.
Moniker: action-hub
Tags:
  - mcp
  - cli
  - developer-tools
ManifestType: defaultLocale
ManifestVersion: ${MANIFEST_VERSION}
`;

  const installerManifest = `# Generated by scripts/gen-winget.mjs. Do not edit by hand.
PackageIdentifier: ${PACKAGE_ID}
PackageVersion: ${version}
InstallerType: portable
Commands:
  - action-hub
ReleaseDate: ${new Date().toISOString().slice(0, 10)}
Installers:
  - Architecture: x64
    InstallerUrl: ${base}/action-hub-windows-x64.exe
    InstallerSha256: ${shaUpper}
ManifestType: installer
ManifestVersion: ${MANIFEST_VERSION}
`;

  await mkdir(outDir, { recursive: true });
  await writeFile(resolve(outDir, `${PACKAGE_ID}.yaml`), versionManifest);
  await writeFile(resolve(outDir, `${PACKAGE_ID}.locale.en-US.yaml`), localeManifest);
  await writeFile(resolve(outDir, `${PACKAGE_ID}.installer.yaml`), installerManifest);
  process.stderr.write(`Wrote winget manifests to ${outDir} (v${version})\n`);
}

main().catch((err) => {
  process.stderr.write(`gen-winget failed: ${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
